### ISSUE TITLE
tailf-common module loading failed

### ISSUE THREAD

**Issue by rabhat31** [CESNET/libyang#1856] opened 2022-05-26 21:50 UTC
Hi, I'm running into an issue when loading the "tailf-common" module on my system.

libyang[0]: Extension definition of extension instance "tailf:use-in" not found. (path: /tailf-common:{identity='yang-lib-id'}/{extension='tailf:abstract'}/{extension='abstract'}/{extension='tailf:use-in'})
libyang[0]: Loading "tailf-common" module failed. (path: /tailf-common:{identity='yang-lib-id'})

What steps can I take to debug this further? Using v2.0.194.

**Comment by michalvasko** [comment] 2022-05-27 06:02
Provide the exact command to reproduce, when simply loading the [module](https://github.com/YangModels/yang/blob/main/vendor/cisco/xe/1671/tailf-common.yang) using `yanglint`, I got no error.

**Comment by rabhat31** [comment] 2022-05-27 19:25
This is the version I'm using. I didn't see an issue with 1671. 

yang/vendor/cisco/xe/1781
> add tailf-common.yang
libyang[0]: Module "tailf-cli-extensions" parsed with the wrong revision ("2020-11-26" instead "2017-08-23").
libyang[0]: Parsing submodule "tailf-cli-extensions" failed.
libyang[0]: Including "tailf-cli-extensions" submodule into "tailf-common" failed.
libyang[0]: Parsing module "tailf-common" failed.
>

Is this a matter of updating the tailf-cli-extensions.yang file?

**Comment by michalvasko** [comment] 2022-05-30 07:31
It seems `tailf-common` has an include for `talf-cli-extensions` with a `revision-date` and the specific revision cannot be found so make sure that it can by setting the search directory correctly, for example.

**Comment by rabhat31** [comment] 2022-05-31 16:57
Here is another error that we run into based on the cisco-ia module. I'm not sure whether this fails on libyang 2.0 because of a failure to load the tail-f module?

yang model: https://github.com/YangModels/yang/tree/main/vendor/cisco/xe/16121

v1.0.240
$ pwd
/home/test/libyang/build
$ LIBYANG_EXTENSIONS_PLUGINS_DIR="`pwd`/src/extensions" LIBYANG_USER_TYPES_PLUGINS_DIR="`pwd`/src/user_types" ./yanglint
> searchpath /home/test/ws/yang-model/vendor/cisco/xe/16121
> load cisco-ia
>

master
$ pwd
/home/test/libyang/build
$ ./yanglint
> searchpath /home/test/ws/yang-model/vendor/cisco/xe/16121
> load cisco-ia
libyang[0]: Extension definition of extension instance "tailf:use-in" not found. (path: /cisco-ia:{extension='tailf:error-info'}/{extension='error-info'}/{extension='tailf:use-in'})
>

**Comment by michalvasko** [comment] 2022-06-01 06:56
The error is correct, there is no definition of the extension `talf:in-use` at least I could not find it and neither could *libyang*.

**Comment by rabhat31** [comment] 2022-06-01 07:13
I'm a little unclear about the issue here. Why is this working on libyang 1.240 but not master? Reformatted the earlier comment so the output is neater.

**Comment by michalvasko** [comment] 2022-06-01 07:15
Because the old *libyang* was not parsing the nested extension, which does not really surprise me as it is inside another extension. In any case, the current behavior is correct.

**Comment by rabhat31** [comment] 2022-06-01 07:20
I see. So it just silently failed loading that module?

**Comment by michalvasko** [comment] 2022-06-01 07:46
No, *libyang* v1 loaded the module successfully but without the nested extension, it was not parsed at all.

**Comment by rabhat31** [comment] 2022-06-03 00:49
Hi @michalvasko , 
I have a little more clarity into the issue.

Yang models used for testing:
https://github.com/YangModels/yang/tree/main/vendor/cisco/xe/1781

yanglint/libyang v2.0.194

Experiment:
> searchpath ../../../test_yang/yang/vendor/cisco/xe/1781
> add ../../../test_yang/yang/vendor/cisco/xe/1781/tailf-common.yang
> libyang[0]: Extension definition of extension instance "tailf:use-in" not found. (path: /tailf-common:{identity='yang-lib- id'}/{extension='tailf:abstract'}/{extension='abstract'}/{extension='tailf:use-in'})

As you can see, there is an error with the extension parsing. Seems to be an issue when parsing the tailf:abstract extension. I modified the yang model by removing 1 line for testing:

diff --git a/vendor/cisco/xe/1781/tailf-common.yang b/vendor/cisco/xe/1781/tailf-common.yang
index 4880d3be..e906c081 100644
--- a/vendor/cisco/xe/1781/tailf-common.yang
+++ b/vendor/cisco/xe/1781/tailf-common.yang
@@ -850,7 +850,6 @@ module tailf-common {

   identity yang-lib-id {
     base mount-id;
-    tailf:abstract;
   }

   /*

WIth this modified file, libyang is able to parse the tailf-common.yang model

rdb@sdg989:~/yanglint/libyang/build$ ./yanglint
> searchpath ../../../test_yang/yang/vendor/cisco/xe/1781
> add ../../../test_yang/yang/vendor/cisco/xe/1781/tailf-common.yang

Further validation:
I have also tried to validate these models on 
https://yangcatalog.org/yangvalidator
  
The results are:
Pyang Validation
No warnings or errors

Confdc Validation
No warnings or errors

Yanglint Validation
libyang err : Extension definition of extension instance "tailf:use-in" not found. (/tailf-common:{identity='yang-lib-id'}/{extension='tailf:abstract'}/{extension='abstract'}/{extension='tailf:use-in'})

YANGLINT[E]: Parsing schema module "yangvalidator-v2-workdir-coFbaHWH/tailf-common.yang" failed.
Yangdump-pro Output
No warnings or errors 

Validators versions: confd: confd-7.6    pyang: 2.5.3    xym: 0.5    yangdump: 20.10-9    yanglint: 2.0.194

**Comment by michalvasko** [comment] 2022-06-08 06:14
So this issue should be fixed but there are still memory leaks when freeing these modules that I have not been able to solve yet. Hopefully, in the next days I will but the memory management is really complex in this case.

**Comment by rabhat31** [comment] 2022-06-08 16:27
Thanks Michal. Let me try and verify the fix.

**Comment by rabhat31** [comment] 2022-06-08 18:16
Tried on latest devel. I get a segfault when trying to load these modules with yanglint. Is this related to the memory error?

df34af7e (HEAD -> devel, origin/devel) VERSION bump to version 2.0.216

> searchpath ../../../test_yang/yang/vendor/cisco/xe/1781
> verb debug
> add ../../../test_yang/yang/vendor/cisco/xe/1781/tailf-common.yang
...
libyang[2]: Loading schema from "/home/rdb/test_yang/yang/vendor/cisco/xe/1781/tailf-meta-extensions.yang" file.
...
libyang[2]: Loading schema from "/home/rdb/test_yang/yang/vendor/cisco/xe/1781/tailf-cli-extensions.yang" file.
Segmentation fault

**Comment by michalvasko** [comment] 2022-06-09 05:58
Sorry, I have forgotten to push another path of the fix, try now.

**Comment by rabhat31** [comment] 2022-06-09 17:12
Thanks @michalvasko . Both tailf-common and cisco-ia models load without errors now.

**Closed** 2022-07-26 13:55 UTC
Labels: is:bug, status:completed
