### ISSUE TITLE
libyang2 fails to load modules

### ISSUE THREAD

**Issue by alajebnoun** [CESNET/libyang#2185] opened 2024-02-25 23:11 UTC
Python 3.10.12 ; libyang 2.8.4
When trying to load a yang module I'm getting the following error:

>>> import libyang
>>> ctx = libyang.Context('/root/yang-modules')
>>> module = ctx.load_module('telemety-config')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/venv/lib/python3.10/site-packages/libyang/context.py", line 168, in load_module
    raise self.error("cannot load module")
libyang.util.LibyangError: cannot load module: Extension instance "ncs:ncs-service-private" refers "tailf-ncs" module that does not contain extension definitions.: Parsing module "tailf-ncs" failed.: Loading "tailf-ncs" module failed.: Parsing module "telemety-config" failed.: Loading "telemety-config" module failed.

Any idea if this is a bug from libyang ?

**Comment by michalvasko** [comment] 2024-02-26 07:05
Yes, most likely this is caused by a bug that has been fixed in version 2.1.157 (SO 2.48.2) based on an [issue](#2164).

**Comment by alajebnoun** [comment] 2024-02-26 07:23
> Yes, most likely this is caused by a bug that has been fixed in version 2.1.157 (SO 2.48.2) based on an [issue](#2164).

Was the version 2.1.157 released ?

**Comment by michalvasko** [comment] 2024-02-26 08:15
No, the patch is still in the `devel` branch for now.

**Closed** 2024-12-02 14:04 UTC
Labels: is:bug, status:duplicate
