### ISSUE TITLE
some question of the namespce in xml that printed by  lyd_print_mem 

### ISSUE THREAD

**Issue by ostack** [CESNET/libyang#199] opened 2016-11-16 11:16 UTC
when i use  lyd_print_mem to print lyd_node to xml , i found there is some confuse things on namespace, like : 
1. Sometimes the root node has two  alias of the same namespace ,somttimes it only has one.  When there is two alias appear, the alias are not equal , one is with model prefix, and the other not .like sample one.
2. when the root node does not contain any element of the root model ,but only have the augment model element data ,both of the root node and the augment root node 's namespace alias name  do not have model prefix.
3. according to the condition 2, when the node of augment module 's node has attribute ,the attribute name have the augment model prefix ,but the prefix not appear on the alias of the namespace. like the sample two

------sample one-------
```xml
<Ostack **xmlns="urn:Ostack:params:xml:ns:yang:ran:Ostack"** **xmlns:Ostack="urn:Ostack:params:xml:ns:yang:ran:Ostack">**
  <meId>121</meId>
</Ostack>
```

------sample two-------
```xml
<Ostack **xmlns="urn:Ostack:params:xml:ns:yang:ran:Ostack"** 
  <fox **xmlns="urn:Ostack:params:xml:ns:yang:ran:fox"**>
        <fireFox **fox:oper="create"**> ---oper prefix for not define
          <nID>255</nID>
          <sID>3</sID>
        </fireFox>
  </fox>
</Ostack>
```

**Comment by michalvasko** [comment] 2016-11-18 08:05
Hi,
these issues require a complex solution and will be fixed together with another new feature, hence it will take a few weeks.

Regards,
Michal

**Comment by rkrejci** [comment] 2017-01-09 13:43
Hi,
I have some additional questions to this.

ad 1. -  can you provide instructions to reproduce the issue? Mainly the schema and data to parse and then print. Valid situation is that the prefixed namespace is used for example in instance-identifier value, but that is not the case of your sample one, so I'm interesting how I can create such an output.

ad 2. - that is a valid output, the nodes just changes the default namespace and I don't see any issue with this.

ad 3. - this is connected with the support for YANG annotations, so the problem can remain until libyang will support them. The other option is to disable (change the libyang current behavior) attributes in the data nodes.

**Comment by rkrejci** [comment] 2017-02-28 09:45
HI, I have implemented ietf-metadata (annotations) in the devel branch. It should solve the issues with XML attributes - all the attributes are now supposed to be defined in the YANG schemas as annotations. If you can, please try the current devel and provide feedback. Note, that since the annotations support is implemented via plugins, libyang must be installed or the plugins directory must be correctly set (see the [README](https://github.com/CESNET/libyang/blob/devel/README.md)).

**Comment by rkrejci** [comment] 2017-03-09 13:30
Support for ietf-metadata is now available in master branch. Because of missing responce, I'm closing this issue.

**Closed by rkrejci** 2017-03-09 13:30 UTC
