### ISSUE TITLE
lys_parse_path tries to perform validation

### ISSUE THREAD

**Issue by milanlenco** [CESNET/libyang#222] opened 2016-12-15 07:34 UTC
Tests in sysrepo started to fail because `lys_parse_path` apparently attempts to execute a validation before actual data are loaded and fails.

In one of the tests we create an empty libyang context and call lys_parse_path on `md_test_module-B.yang`, which fails with:
```
libyang[0]: Unknown module "md_test_module-A" relative to the context node "/md_test_module-B:tax-enabled".
libyang[0]: Resolving when condition "/md_test_module-A:base-container/name = 'tax authority'" failed. (path: /md_test_module-B:tax-enabled)
libyang[0]: Submodule "md_test_submodule-Bs1" parsing failed.
libyang[0]: Including "md_test_submodule-Bs1" module into "md_test_module-B" failed.
libyang[0]: Module "md_test_module-B" parsing failed.
```

Here are all the involved modules:

`md_test_module-A.yang`:
```
module md_test_module-A {
  namespace "urn:ietf:params:xml:ns:yang:A";
  prefix A;
  organization "sysrepo.org";
  description "module used by md_test referenced as 'A'";
  contact "sysrepo-devel@sysrepo.org";

  container base-container{
    description "Trivial container which is augmented by other modules.";
    leaf name {
      type string;
    }
    leaf num {
      type int16;
    }
  }

  identity base-identity {
    description "Base identity from which specific identities are derived.";
  }
}
```

`md_test_module-B.yang`:
```
module md_test_module-B {
  namespace "urn:ietf:params:xml:ns:yang:B";
  prefix B;
  include md_test_submodule-Bs1;
  include md_test_submodule-Bs2;
  include md_test_submodule-Bs3;
  organization "sysrepo.org";
  description "module used by md_test referenced as 'B'";
  contact "sysrepo-devel@sysrepo.org";

  container inst-ids {
    leaf-list inst-id {
      type instance-identifier;
    }
  }
}
```

`md_test_submodule-Bs1.yang`:
```
submodule md_test_submodule-Bs1 {
  belongs-to md_test_module-B {
    prefix B;
  }
  import md_test_module-A {
    prefix A;
  }
  organization "sysrepo.org";
  description "submodule used by md_test referenced as 'Bs1'";
  contact "sysrepo-devel@sysrepo.org";

  identity B-ext-identity {
    base A:base-identity;
  }

  leaf tax-enabled {
    when "/A:base-container/name = 'tax authority'";
    type boolean;
  }
}
```

`md_test_submodule-Bs2.yang`:
```
submodule md_test_submodule-Bs2 {
  belongs-to md_test_module-B {
    prefix B;
  }
  import md_test_module-A {
    prefix A;
  }
  organization "sysrepo.org";
  description "submodule used by md_test referenced as 'Bs2'";
  contact "sysrepo-devel@sysrepo.org";

  augment "/A:base-container" {
    leaf B-ext-leaf {
      type uint32;
    }
    leaf B-ext-inst-id {
      type instance-identifier;
    }
    leaf B-ext-op-data {
       type uint32;
       config false;
    }
    leaf avoid-data-loop {
      type leafref {
        path "/A:base-container/B:B-ext-leaf";
      }
    }
  }

  leaf B-data-deps-on-A {
    type leafref {
      path "/A:base-container/B:B-ext-leaf";
    }
  }
}
```

`md_test_submodule-Bs3.yang`:
```
submodule md_test_submodule-Bs3 {
  belongs-to md_test_module-B {
    prefix B;
  }
  organization "sysrepo.org";
  description "submodule used by md_test referenced as 'Bs3'";
  contact "sysrepo-devel@sysrepo.org";

  container op-data {
    config false;
    leaf-list list-with-op-data {
      type string;
    }
    container nested-op-data {
      leaf nested-leaf1 {
        type string;
      }
      leaf nested-leaf2 {
        type int8;
      }
    }
  }
}
```

**Comment by lukasmacko** [comment] 2016-12-19 08:23
imho the issue is that if the import is defined only in submodules libyang doesn't load the dependant module. If I add
```
import md_test_module-A {
    prefix A;
}
````
into `md_test_module-B.yang` it works with the following code and the modules listed above located in the working dir 

```C
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>

int main(int argc, char **argv)
{
   struct ly_ctx *ctx = ly_ctx_new(".");
   lys_parse_path(ctx, "md_test_module-B.yang", LYS_IN_YANG);
   ly_ctx_destroy(ctx, NULL);
}

```

**Comment by michalvasko** [comment] 2016-12-20 13:20
Hi,
it should be fixed.

Michal

**Closed by michalvasko** 2016-12-20 13:20 UTC
