### ISSUE TITLE
"No resolvents found for leafref" when target leaf is in grouping?

### ISSUE THREAD

**Issue by dmcpriv** [CESNET/libyang#109] opened 2016-09-01 20:01 UTC
I am getting unresolved leafrefs when I load my modules, and it *seems* to be related to the fact that the leaf itself is defined in a grouping.

Does anybody know if resolve will follow "uses" references when trying to resolve paths?

**Comment by michalvasko** [comment] 2016-09-02 07:03
Hi,
yes, it should all work no matter where the leafref points to. Please share your module if you want us to help, thanks.

Regards,
Michal

**Comment by dmcpriv** [comment] 2016-09-02 14:21
Here are the two modules:

```xml
<module name="d" xmlns="urn:ietf:params:xml:ns:yang:yin:1" xmlns:d="d">
  <namespace uri="d"/>
  <prefix value="d"/>
  <import module="r"> <prefix value="r"/> </import>
  <organization> <text>d</text> </organization>
  <contact> <text>d</text> </contact>
  <description> <text>d</text> </description>
  <revision date="2001-01-01"> <description> <text>1</text> </description> </revision>
  <grouping name="b">
    <leaf name="a">
      <type name="string"/>
    </leaf>
  </grouping>
  <container name="d">
    <container name="c">
      <uses name="b"/>
    </container>
  </container>
</module>

```

```xml
<module name="r" xmlns="urn:ietf:params:xml:ns:yang:yin:1" xmlns:r="r">
  <namespace uri="r"/>
  <prefix value="r"/>
  <organization> <text>r</text> </organization>
  <contact> <text>r</text> </contact>
  <description> <text>r</text> </description>
  <revision date="2001-01-01"> <description> <text>1</text> </description> </revision>
  <grouping name="x">
    <leaf name="y">
      <type name="leafref">
        <path value="/d/c/a"/>
      </type>
    </leaf>
  </grouping>
</module>
```

When I load "d" via libyang, it imports "r" and I get the following error:

```
libyang[1]: No resolvents found for leafref "/d/c/a". (path: /r:x/y)
libyang[1]: Module "d" parsing failed.

```

**Comment by dmcpriv** [comment] 2016-09-02 14:22
I kind of suspect that leafrefs should be parsed against the "unfolded" node (where they are used) and not in the grouping itself, since the context may not be known.

**Comment by michalvasko** [comment] 2016-09-02 14:31
Hi,
you are right, this is a problem in the current libyang master branch. It is fixed in the devel branch, but it will still take some time until it gets merged into master, so I suggest you use devel if you can.

Regards,
Michal

**Closed by michalvasko** 2016-09-02 14:31 UTC

**Comment by dmcpriv** [comment] 2016-09-02 14:36
Thanks.  How localized is the change?  I am worried about pulling in other bugs from devel, but I can patch my branch if needed

**Comment by michalvasko** [comment] 2016-09-02 14:49
Actually, it should be the other way around, we fixed several things in devel. The problem is that we also started adding YANG 1.1 features and changed API, so be ready for that if you use devel.

Regards,
Michal

**Comment by dmcpriv** [comment] 2016-09-02 14:50
Okay, so is the expectation that devel is stable enough to use if I am okay to use the new API, etc?  I am using libyang combined with libnetconf2.  would the API change impact that, or is there a libnetconf2 devel stream I would need to use as well?

**Comment by dmcpriv** [comment] 2016-09-02 22:00
Actually looking at https://tools.ietf.org/html/rfc6020#page-29, section 5.4, it seems like the YANG is invalid since the paths cannot be resolved in the context of the grouping.  

Is it valid that this can now be parsed in the devel branch?

**Comment by michalvasko** [comment] 2016-09-05 06:56
Hi,
regarding your first post, yes, you either use master branches of libyang, libnetconf2, and netopeer2 or you use devel branches of them all. sysrepo might not always work with our devel branches, though.

As for leafref in a grouping, it is not invalid as long as you don't use it anywhere. Technically, you cannot verify whether it's valid or invalid unless some uses references it.

Regards,
Michal

**Comment by rkrejci** [comment] 2016-09-05 09:17
One note about the fix in devel - since we already implemented a lot of features from YANG 1.1, the code in devel differs from master quite lot and instead of porting some of the bugfixes back to the two branches, we have decided (in case of more complex bugfixes - when a simple cherry-pick is not possible) focus only to the devel branch with YANG 1.1. That's the reason why some issues are solved only in the current devel branch. 

On the other hand, because we still implement the rest of YANG 1.1 features, the devel branch changes often and it is not as stable as master and all the new commits can introduce new bugs.

**Comment by dmcpriv** [comment] 2016-09-05 11:35
Thanks everyone for their responses.  I think I will choose to rework the model to avoid this questionable behavior, and stay with the master branch for now.  Good to know what to do if I do need to move to devel though.

Also, the RFC reference does seem to make it clear that resolutions must be unambiguous and be resolvable only the context they are defined in, not the context they are used in, but I am probably missing some subtlety:

```
Grouping, type, and identity names are resolved in the context in
   which they are defined, rather than the context in which they are
   used.  Users of groupings, typedefs, and identities are not required
   to import modules or include submodules to satisfy all references
   made by the original definition.  This behaves like static scoping in
   a conventional programming language.

   For example, if a module defines a grouping in which a type is
   referenced, when the grouping is used in a second module, the type is
   resolved in the context of the original module, not the second
   module.  There is no worry over conflicts if both modules define the
   type, since there is no ambiguity.
```

**Comment by michalvasko** [comment] 2016-09-05 13:03
Be careful, not all resolutions, it explicitly mentions `groupings`, `types`, and `identities`. The rest (such as a leafref) is resolved only in uses referencing that particular grouping.

Regards,
Michal

**Comment by davemiedema** [comment] 2016-09-05 13:07
Ah yes.  Makes sense.  Thanks!
