### ISSUE TITLE
Failure of xml in parsing string pattern

### ISSUE THREAD

**Issue by amandeepsethi** [CESNET/libyang#699] opened 2019-01-21 10:05 UTC
Hi,

I am working on YANG models and came across a scenario where one of the defined schema is failed in parsing the data passed to the "lyd_parse_mem" API.

Following are the errors logs observed:
**libyang[2]: Plugin "/usr/local/lib64/libyang/extensions/nacm.so" successfully loaded.
libyang[2]: Plugin "/usr/local/lib64/libyang/extensions/metadata.so" successfully loaded.
libyang[2]: Plugin "/usr/local/lib64/libyang/extensions/yangdata.so" successfully loaded.
libyang[2]: Plugin "/usr/local/lib64/libyang/user_types/user_date_and_time.so" successfully loaded.
libyang[2]: Reading module "ietf-yang-metadata".
libyang[2]: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
libyang[2]: Reading module "yang".
libyang[2]: Resolving "yang" unresolved schema nodes and their constraints...
libyang[2]: All "yang" schema nodes and constraints resolved.
libyang[2]: Module "yang@2017-02-20" successfully parsed as implemented.
libyang[2]: Reading module "ietf-inet-types".
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
libyang[2]: All "ietf-inet-types" schema nodes and constraints resolved.
libyang[2]: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
libyang[2]: Reading module "ietf-yang-types".
libyang[2]: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
libyang[2]: Reading module "ietf-datastores".
libyang[2]: Module "ietf-datastores@2017-08-17" successfully parsed as implemented.
libyang[2]: Reading module "ietf-yang-library".
libyang[2]: Module "ietf-yang-library@2018-01-17" successfully parsed as implemented.
libyang[2]: Searching for "parent" in /localdisk/libyang/yang_models.
libyang[2]: Loading schema from "/localdisk/libyang/yang_models/parent.yang" file.
libyang[2]: Module "parent" successfully parsed as implemented.
libyang[0]: Value "1.1.1.1" does not satisfy the constraint "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$" (range, length, or pattern). (path: /parent:ip)
Failed in parsing xmlStr**

Attached is the YANG model used and code to show the issue.
Note: Used the latest libyang code for verification i.e. **0.16.105**

[Issue.zip](https://github.com/CESNET/libyang/files/2778456/Issue.zip)

**Comment by michalvasko** [comment] 2019-01-21 10:16
Hi,
the pattern is wrong, please take a look at the referenced issue for explanation.

Regards,
Michal

Duplicate of #422

**Closed by michalvasko** 2019-01-21 10:16 UTC
Labels: duplicate

**Comment by amandeepsethi** [comment] 2019-01-21 10:21
Thanks for pointing out the issue and the fix.
