### ISSUE TITLE
setting value of leaf of augmented table

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/libyang#792] opened 2019-05-27 09:06 UTC
Hello,
I am facing difficulties with setting the value of a leaf of an augmented table that requires a feature to be enabled. I am augmenting the ietf-interfaces table with ieee802-ethernet-interface.  One of the containers of the latter table is pfc that requires the ethernet-pfc feature to be enabled. After enabling the feature, I am not able to set the enable leaf of the pfc container, the following error occurs:
[ERR] libyang error: Target context does not contain schema node for the data node being duplicated (ieee802-ethernet-interface:pfc).

Regards

**Comment by michalvasko** [comment] 2019-05-27 13:53
Hi,
I would need more details. For starters, you are using *libyang* directly, no *sysrepo*/*netopeer2-server*? Either way, please describe the steps done to get the error, with any used data trees if required.

Regards,
Michal

**Comment by gitter-runner** [comment] 2019-05-28 09:03
Hello,
I am using sysrepo, and it gives a libyang error. Shall I post the issue there with the relevant data and logs?

The steps:

Initial state of sysrepo:
```

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-acm           | 2018-02-14 | Installed   | root:cli_users      | 660         |                               |
ietf-interfaces            | 2018-02-20 | Installed   | root:cli_users      | 660         |                               | arbitrary-names pre-provisioning if-mib
iana-if-type               | 2018-07-03 | Installed   |                     |             |                               |
ieee802-types              | 2018-03-07 | Installed   |                     |             |                               |
ieee802-dot1q-types        | 2018-03-07 | Installed   |                     |             |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:cli_users      | 660         |                               | xpath
ietf-netconf-notifications | 2012-02-06 | Installed   | root:cli_users      | 660         |                               |
ietf-system                | 2014-08-06 | Installed   | root:cli_users      | 660         |                               | authentication radius
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |
ietf-interface-protection  | 2018-06-30 | Installed   |                     |             |                               |
ieee802-ethernet-interface | 2018-05-31 | Installed   |                     |             |                               |
ieee802-dot1q-bridge       | 2018-03-07 | Installed   | root:cli_users      | 660         |                               |
iana-hardware              | 2018-03-13 | Installed   |                     |             |                               |
ietf-hardware              | 2018-03-13 | Installed   | root:cli_users      | 660         |                               | hardware-state hardware-sensor entity-mib
ietf-hardware-state        | 2018-03-13 | Installed   | root:cli_users      | 660         |                               | hardware-state hardware-sensor entity-mib                             |

```
Note: no features are enabled for ieee802-ethernet-interface

Writing the config from the following xml:

```
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>LAN 1/1/1</name>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
    <enabled>false</enabled>
    <link-up-down-trap-enable>enabled</link-up-down-trap-enable>
    <ethernet xmlns="urn:ieee:std:802.3:yang:ieee802-ethernet-interface">
      <auto-negotiation>
        <enable>true</enable>
      </auto-negotiation>
      <duplex>full</duplex>
      <speed>1.0</speed>
      <flow-control>
        <force-flow-control>false</force-flow-control>
      </flow-control>
    </ethernet>
  </interface>
</interfaces>
```

Command:
`sysrepocfg -d startup --import=... /xml/conf.xml --format=xml --level=4 ietf-interfaces`

Result:
`The new configuration was successfully applied.`

Displaying the configuration: 
`-bash-4.2# sysrepocfg --format=json --datastore=startup ietf-interfaces`
```
{
  "ietf-interfaces:interfaces": {
    "interface": [
      {
        "name": "LAN 1/1/1",
        "type": "iana-if-type:ethernetCsmacd",
        "enabled": false,
        "link-up-down-trap-enable": "enabled",
        "ieee802-ethernet-interface:ethernet": {
          "auto-negotiation": {
            "enable": true
          },
          "duplex": "full",
          "speed": "1.0",
          "flow-control": {
            "force-flow-control": false
          }
        }
      }
    ]
  }
}
```

Now we enable the pfc-ethernet feature on table ieee802-ethernet-interface: 

`sysrepoctl --feature-enable=ethernet-pfc --module=ieee802-ethernet-interface`

Enabling feature 'ethernet-pfc' in the module 'ieee802-ethernet-interface'.
`Operation completed successfully.`

`sysrepoctl -l`

```
Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-acm           | 2018-02-14 | Installed   | root:cli_users      | 660         |                               |
ietf-interfaces            | 2018-02-20 | Installed   | root:cli_users      | 660         |                               | arbitrary-names pre-provisioning if-mib
iana-if-type               | 2018-07-03 | Installed   |                     |             |                               |
ieee802-types              | 2018-03-07 | Installed   |                     |             |                               |
ieee802-dot1q-types        | 2018-03-07 | Installed   |                     |             |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:cli_users      | 660         |                               | xpath
ietf-netconf-notifications | 2012-02-06 | Installed   | root:cli_users      | 660         |                               |
ietf-system                | 2014-08-06 | Installed   | root:cli_users      | 660         |                               | authentication radius
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |
ietf-interface-protection  | 2018-06-30 | Installed   |                     |             |                               |
ieee802-ethernet-interface | 2018-05-31 | Installed   |                     |             |                               | ethernet-pfc
ieee802-dot1q-bridge       | 2018-03-07 | Installed   | root:cli_users      | 660         |                               |
iana-hardware              | 2018-03-13 | Installed   |                     |             |                               |
ietf-hardware              | 2018-03-13 | Installed   | root:cli_users      | 660         |                               | hardware-state hardware-sensor entity-mib
ietf-hardware-state        | 2018-03-13 | Installed   | root:cli_users      | 660         |                               | hardware-state hardware-sensor entity-mib                              |

```
Now we add new lines to the flow-control settings:

```
      <flow-control>
        <pfc>
          <enable>false</enable>
        </pfc>
        <force-flow-control>false</force-flow-control>
      </flow-control>
```

Result of writing the new configuration:

```
[ERR] Commit operation failed with 2 error(s).
[ERR] Error returned from sr_commit: Validation of the changes failed.
[ERR] (null) : Validation failed: Sysrepo-internal error
[ERR] (null) : Validation failed: Sysrepo-internal error
Errors were encountered during importing. Cancelling the operation.
```

```
sysrepod[2435]: [ERR] libyang error: Target context does not contain schema node for the data node being duplicated (ieee802-ethernet-interface:pfc).
sysrepod[2435]: [ERR] Failed to duplicate ietf-interfaces data tree into another context
sysrepod[2435]: [ERR] Failed to append data tree ietf-interfaces
sysrepod[2435]: [ERR] Loading dependant modules failed for ieee802-dot1q-bridge
sysrepod[2435]: [ERR] Validation after merging failed
```

**Comment by michalvasko** [comment] 2019-06-20 12:11
Duplicate of sysrepo/sysrepo#1505.

**Closed by michalvasko** 2019-06-20 12:11 UTC
