### ISSUE TITLE
Segmentation fault when printing tree if-feature expr "not f1 or (not f1 or not f2)"

### ISSUE THREAD

**Issue by fredgan** [CESNET/libyang#962] opened 2019-11-27 09:20 UTC
Hi,
  I encounter segmentation fault when I test print_tree about if-feature expression. 
  `yang module :`
```
module mod {
     yang-version 1.1;
     namespace "urn:cesnet:mod";
     prefix abc;

     feature f1;
     feature f2;

     grouping g {
        choice ch1 {
            case ca {
                leaf l {
                  type int32;
                }
            }
        }
     }
     container cc {
         uses g {
            refine ch1/ca {
                description "test";
                if-feature "not f1 or (not f1 or not f2)";
            }
         }
     }
}
```
`The result is that:`
```
~test# ./yanglint -f tree mod.yang
module: mod
  +--rw cc
     +--rw (ch1)?
 segmentation fault (core dumped)
```

**Comment by ret2libc** [comment] 2019-11-29 13:55
Which version are you testing? I cannot reproduce on current master (commit 4563cba265403d335be7afedcecaa008bd95ceac)

**Comment by fredgan** [comment] 2019-11-29 14:38
Maybe it's my mistake for the old version. I'll check it tomorrow with my working PC. @ret2libc

**Comment by fredgan** [comment] 2019-11-30 01:51
@ret2libc @rkrejci 
Hi, Radek.   I've checked it! It's the newest version the same with you.

This coredump happens ramdonly while I run this command many times.

**Comment by rkrejci** [comment] 2019-12-05 09:53
Thanks forr reporting, it should be fixed in the devel branch. Master now reflects releases, so I expect it will appear in master during Jan/Feb.

**Closed by rkrejci** 2019-12-05 09:53 UTC
Labels: is:bug, status:completed

**Comment by fredgan** [comment] 2019-12-06 02:43
Hi,
Right, I test it again, it works. Thanks.

Regards,
Fredgan
