### ISSUE TITLE
[ERR] libyang: Unable to parse submodule, parse the main module instead.

### ISSUE THREAD

**Issue by darshana-jk** [CESNET/libyang#303] opened 2017-04-05 13:56 UTC
My packages:
libyang, libnetconf2, Netopeer(server), sysrepo all at latest devel branches (updated today).
My objective is to load the[ bbf-vdsl YANG](https://github.com/BroadbandForum/yang/blob/master/standard/interface/bbf-vdsl.yang) module to sysrepo. This module is a list of other submodules.

At start, I have the standard yang modules loaded as done by the installation of above four packages.
Then I was able to load the bbf-vdsl.yang module with all its submodules to the sysrepo/libyang context. I has some warnings but the operation was successful (full debug log:[bbf-vdsl-libyang-error.txt](https://github.com/CESNET/libyang/files/896427/bbf-vdsl-libyang-error.txt)).

```
sudo sysrepoctl -i -g bbf-vdsl.yang -S -o root:root -p 644 -L 4
...
[WRN] (md_collect_data_dependencies:1375) Failed to get the module schema based on the prefix
...
[WRN] (md_collect_data_dependencies:1375) Failed to get the module schema based on the prefix
Install operation completed successfully.
```
Please note I had to remove the augment sections from the libyang to prevent sysrepoctl from seg-faulting (It looks like this is a known issue), also the sysrepod was not running.
[bbf-vdsl-patch.txt](https://github.com/CESNET/libyang/files/896422/bbf-vdsl-patch.txt)

After that when the module is initialised, libyang give the following error:
```
[/tmp/bbf-yang/standard/interface]$ sudo sysrepoctl -t -r 2016-07-18 -m bbf-vdsl
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
...
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: A circular dependency (import) for module "iana-if-type".
[ERR] (srctl_ly_log_cb:479) libyang: Module "bbf-fastdsl" parsing failed.
[ERR] (srctl_ly_log_cb:479) libyang: Importing "bbf-fastdsl" module into "bbf-vdsl-base" failed.
[ERR] (srctl_ly_log_cb:479) libyang: Submodule "bbf-vdsl-base" parsing failed.
[ERR] (srctl_ly_log_cb:479) libyang: Including "bbf-vdsl-base" module into "bbf-vdsl" failed.
[ERR] (srctl_ly_log_cb:479) libyang: Module "bbf-vdsl" parsing failed.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
...
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: A circular dependency (import) for module "iana-if-type".
[ERR] (srctl_ly_log_cb:479) libyang: Module "bbf-fastdsl" parsing failed.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: A circular dependency (import) for module "notifications".
[ERR] (srctl_ly_log_cb:479) libyang: Module "nc-notifications" parsing failed.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
[ERR] (srctl_ly_log_cb:479) libyang: A circular dependency (import) for module "iana-crypt-hash".
[ERR] (srctl_ly_log_cb:479) libyang: Module "ietf-system" parsing failed.
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
....
[ERR] (srctl_ly_log_cb:479) libyang: Unable to parse submodule, parse the main module instead.
Error: Cannot find schema file for the module 'bbf-vdsl@2016-07-18' in the repository.
Init operation cancelled.
```
Probably the last error is coming from the sysrepoctl code, however I'm not sure where the failure started (in libyang or sysrepo).
I agree that this could be a yang module implementation error in the bbf-vdsl module as well, however I ran it through pyang and didn't get any errors (but still I'm not sure whether pyang will catch circular dependency error though) 
I'm new to the NETCONF-YANG model and to the libyang, libnetconf2, Netopeer, sysrepo system, therefore I'm not yet familiar with the libyang/sysrepo code to debug the issue my self, any insight is greatly appreciated.

**Comment by rkrejci** [comment] 2017-04-05 14:03
This seems as a bug in sysrepo/sysrepoctl caused by some issue in resolving dependencies between the modules. Please create the issue in sysrepo issue tracker. The libyang error messages seems to me caused by invalid input data (submodule instead of main module) from sysrepoctl.

Links to the used modules will be more than appreciated ;)

Btw, why do you think that the segfault issue is known issue?

**Closed by rkrejci** 2017-04-05 14:03 UTC

**Comment by darshana-jk** [comment] 2017-04-05 14:09
The behaviour I'm seeing is similar to this issue:
https://github.com/sysrepo/sysrepo/issues/671

**Comment by rkrejci** [comment] 2017-04-05 14:11
Thanks for link
