### ISSUE TITLE
some time there is some error log，Does anyone come across this situation？What might be the reason

### ISSUE THREAD

**Issue by superandrewaaa** [CESNET/libyang#1218] opened 2020-09-30 08:41 UTC
the libyang version is libyang.so.1.1.30

Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Failed to find "global-lock" as a sibling to "ietf-netconf-monitoring:name".
Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Failed to find "global-lock" as a sibling to "ietf-netconf-monitoring:name".
Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Failed to find "global-lock" as a sibling to "ietf-netconf-monitoring:name".

**Comment by michalvasko** [comment] 2020-09-30 09:52
Please do not create duplicate issues, duplicate of https://github.com/CESNET/netopeer2/issues/726.

**Closed by michalvasko** 2020-09-30 09:52 UTC
