### ISSUE TITLE
Libyang fails to resolve leafref to ietf-keystore entry

### ISSUE THREAD

**Issue by iffy50** [CESNET/libyang#1036] opened 2020-03-19 15:24 UTC
We are seeing a problem when we try and sync-to Netopeer (used with pdns). Libyang is showing an invalid leaferef for the ssh key, although the key exists and the leafref contains a valid entry. This results in the edit-config failing:

This is the output from journalctl:

```
Mar 19 12:03:00 bn831x2a-ns5-lab pdns-sysrepo[758]: libyang[0]: Leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" of value "genkey" points to a non-existing leaf. (path: /ietf-netconf-server:netconf-server/listen/endpoint[name='default-ssh']/ssh/ssh-server-parameters/server-identity/host-key[name='default-key']/public-key/keystore-reference)
Mar 19 12:03:00 bn831x2a-ns5-lab pdns-sysrepo[758]: 2020-03-19 12:03:00.596596 - warning - RemoteBackend::commitTransaction - Changes did not validate. error=Validation failed
Mar 19 12:03:00 bn831x2a-ns5-lab pdns-sysrepo[758]: 2020-03-19 12:03:00.596646 - warning -   Error xpath='/ietf-netconf-server:netconf-server/listen/endpoint[name='default-ssh']/ssh/ssh-server-parameters/server-identity/host-key[name='default-key']/public-key/keystore-reference' message='Leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" of value "genkey" points to a non-existing leaf.'
Mar 19 12:03:00 bn831x2a-ns5-lab pdns-sysrepo[758]: 2020-03-19 12:03:00.596664 - warning -   Error xpath='' message='Validation failed.'
```

Relevant parts of the running config (from sysrepocfg):
```
<keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
  <asymmetric-keys>
    <asymmetric-key>
      <name>genkey</name>
      <algorithm>rsa2048</algorithm>
      <public-key>MIIBIjANB etc.</public-key>
      <private-key>MIIEvwIBADANB etc.</private-key>
```
and:
```
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>default-ssh</name>
      <ssh>
        <tcp-server-parameters>
          <local-address>::</local-address>
          <keepalives>
            <idle-time>1</idle-time>
            <max-probes>10</max-probes>
            <probe-interval>5</probe-interval>
          </keepalives>
        </tcp-server-parameters>
        <ssh-server-parameters>
          <server-identity>
            <host-key>
              <name>default-key</name>
              <public-key>
                <keystore-reference>genkey</keystore-reference>
              </public-key>
            </host-key>
```
These entries were created using the scripts (merge_config.sh and merge-hostkey.sh) provided.

libyang 1.0.131-1
libsysrepo v1.4.7 (SO v5.0.7)
Netopeer2 is from devel with commit ID - a26b07a981009754c4836f483f45e1f3f1a9aef4
Libnetconf2  is from devel with commit ID c88f6b396f8c7bbc9fd9151f0e28ed8d7248ddce

These are pinned to older commits, before ietf-yang-libarary was updated to avoid a version mismatch with the older yang-library module in Cisco NSO

**Comment by michalvasko** [comment] 2020-03-19 17:35
Hi,
I do not know what "sync-to Netopeer" means exactly so I really don't know what to look for. Ideally, if you found of way of reproducing this without any external software just by executing some NETCONF command (which is all that happens underneath).

Also, I have committed a possible fix for the NSO yang-library mismatch (https://github.com/CESNET/libnetconf2/commit/d5ada129763bc118d9f61aeeb6f9f24ed3a2321c) but I am not sure what exactly it expects so it may or may not work. Please try it with all the latest `devel` versions.

Regards,
Michal

**Comment by nbkowalewski** [comment] 2020-03-19 23:28
The NSO command "request sync-to" will align the local device config of the device with the one stored on NSO.  In this case, it will first get-config, and then edit-config add another listener address, and one zone in the device. And from the NSO message logs, this IMHO looks fine. 
[netconf-pdns-slave.trace-2020031912.log](https://github.com/CESNET/libyang/files/4357307/netconf-pdns-slave.trace-2020031912.log)

**Comment by nbkowalewski** [comment] 2020-03-19 23:41
After the communication with NSO is completed, the next steps are happening locally on the device - the pdns-sysrepo.service on the DNS slave then learns, that a new empty zone exists on the slave, and acquires the zone data from the master through the DNS protocol (NOTIFY/AXFR).

**Comment by nbkowalewski** [comment] 2020-03-19 23:43
The next step is that locally, on device, the the pdns-sysrepo.service on the DNS slave tries to add the content of the zone if has received in the sysrepo data store, which is the portion that fails in verify with the respective XPATH error.

**Comment by nbkowalewski** [comment] 2020-03-20 00:01
pdns-sysrepo picks up the config from the NSO commit lust fine, and updates the config correctly - only when the changes of the zone content are added in the datastore, the verify of the patched zone data fails with the XPATH error.
[journalctl-pdns-sysrepo-2020-03-19-1159.log](https://github.com/CESNET/libyang/files/4357366/journalctl-pdns-sysrepo-2020-03-19-1159.log)

**Comment by iffy50** [comment] 2020-03-20 07:48
@michalvasko, we're working on steps to reproduce and will update when we've got them.

**Comment by pieterlexis** [comment] 2020-03-20 08:17
I'll interject as well and describe when this error occurs.

On the machine that @iffy50 is describing, netopeer2 is used as NETCONF server. Apart from that, [pdns-sysrepo](https://github.com/PowerDNS/pdns-sysrepo/) is using sysrepo as well. This error occurs on `sr_validate` of <operational> after several calls to `sr_set_item_str` ([here](https://github.com/PowerDNS/pdns-sysrepo/blob/master/src/remote-backend/transactions.cc#L136)).  pdns-sysrepo only writes to `/pdns-server:zones/`, but the validation fails at an unrelated xpath (`/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name`).

I have not looked at sysrepo or netopeer code in detail to find out why this happens, but I have the idea that the leaf-ref's target is not in <operational> (either set, via the model _or_ via a callback in netopeer-server).

**Comment by michalvasko** [comment] 2020-03-20 10:00
Hi,
okay, there are way too many components for me to even guess what is happening so I will need more specific information. The very first log where all the NETCONF requests and replies are seen is very clear and if could get that for all the communication, the error should be discovered easily.

I have just one warning (someone else encountered a similar problem in another issue recently), be careful when executing `copy-config` with a specific config data because the operation replace **the whole datastore** meaning if there are no data for a module, those module data will be completely deleted.

Regards,
Michal

**Comment by pieterlexis** [comment] 2020-03-20 11:55
I managed to reproduce the issue with a tiny application.

Current versions:

```
root@pieter-sysrepo:~# sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.26 (SO v5.1.11)
root@pieter-sysrepo:~# yanglint -v
yanglint SO 1.6.22
```

Here's the installed modules:

```
root@pieter-sysrepo:~# sysrepoctl -l
Sysrepo repository: /etc/sysrepo

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features                                                               
----------------------------------------------------------------------------------------------------------------------------------------------------------------
dns-zone-common            | 2017-01-12 | I     | root:root | 600         |            |                                                                        
iana-crypt-hash            | 2014-08-06 | I     | root:root | 600         |            |                                                                        
iana-dns-class-rr-type     | 2019-06-27 | I     | root:root | 600         |            |                                                                        
iana-dns-parameters        | 2016-08-03 | I     | root:root | 600         |            |                                                                        
ietf-crypto-types          | 2019-07-02 | I     | root:root | 600         |            |                                                                        
ietf-datastores            | 2017-08-17 | i     |           |             |            |                                                                        
ietf-inet-types            | 2013-07-15 | I     | root:root | 600         |            |                                                                        
ietf-keystore              | 2019-07-02 | I     | root:root | 600         |            | keystore-supported                                                     
ietf-netconf               | 2013-09-29 | I     | root:root | 600         |            | writable-running candidate rollback-on-error validate startup url xpath
ietf-netconf-acm           | 2018-02-14 | I     | root:root | 600         |            |                                                                        
ietf-netconf-monitoring    | 2010-10-04 | I     | root:root | 600         |            |                                                                        
ietf-netconf-nmda          | 2019-01-07 | I     | root:root | 600         |            |                                                                        
ietf-netconf-notifications | 2012-02-06 | I     | root:root | 600         |            |                                                                        
ietf-netconf-server        | 2019-07-02 | I     | root:root | 600         |            | ssh-listen ssh-call-home                                               
ietf-netconf-with-defaults | 2011-06-01 | I     | root:root | 600         |            |                                                                        
ietf-origin                | 2018-02-14 | I     | root:root | 600         |            |                                                                        
ietf-ssh-common            | 2019-07-02 | I     | root:root | 600         |            |                                                                        
ietf-ssh-server            | 2019-07-02 | I     | root:root | 600         |            | local-client-auth-supported                                            
ietf-tcp-client            | 2019-07-02 | I     | root:root | 600         |            |                                                                        
ietf-tcp-common            | 2019-07-02 | I     | root:root | 600         |            | keepalives-supported                                                   
ietf-tcp-server            | 2019-07-02 | I     | root:root | 600         |            |                                                                        
ietf-tls-common            | 2019-07-02 | I     | root:root | 600         |            |                                                                        
ietf-tls-server            | 2019-07-02 | I     | root:root | 600         |            |                                                                        
ietf-truststore            | 2019-07-02 | I     | root:root | 600         |            |                                                                        
ietf-x509-cert-to-name     | 2014-12-10 | I     | root:root | 600         |            |                                                                        
ietf-yang-library          | 2019-01-04 | I     | root:root | 600         |            |                                                                        
ietf-yang-metadata         | 2016-08-05 | i     |           |             |            |                                                                        
ietf-yang-types            | 2013-07-15 | i     |           |             |            |                                                                        
nc-notifications           | 2008-07-14 | I     | root:root | 600         |            |                                                                        
notifications              | 2008-07-14 | I     | root:root | 600         |            |                                                                        
pdns-server                | 2020-02-13 | I     | root:root | 600         |            | rrset-management                                                       
yang                       | 2017-02-20 | I     | root:root | 600         |            |                                                                        

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes
```

Here's the contents of <running>:
```json
{
  "ietf-keystore:keystore": {
    "asymmetric-keys": {
      "asymmetric-key": [
        {
          "name": "genkey",
          "algorithm": "rsa2048",
          "public-key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzE1TO9WjsS3B2w/TmPXH\u000A6hZzUR53ek+r159RaGaeWqsLz/OjzlvN7B62MpM/3WpqrL8aI6ksxq4X96Cq183b\u000Az11wUY08qxPuDJuAfYKD4LLTc97svJJDi5o6fMingIpjBVQcektOqe7Ns/3YgVxE\u000AkpYHFD5V/gTbO+Ae67dWiUoJRE9emAzz+egFGYbbzxnaiL1kFmaleUE8vs47DY9W\u000AuUrwXtN+as1iaeGpu8yayQ1QmdeS1AhVeIyHbRSYl3ooykrowA+2Cb2Dx7ONFVTB\u000AtlsPTzTPuZ18E8uMUIDiYQ2QOModX5HYudQWMA9mVVJyGqs/DFCoKGAvJ+G9T4o4\u000A4QIDAQAB",
          "private-key": "MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDMTVM71aOxLcHb\u000AD9OY9cfqFnNRHnd6T6vXn1FoZp5aqwvP86POW83sHrYykz/damqsvxojqSzGrhf3\u000AoKrXzdvPXXBRjTyrE+4Mm4B9goPgstNz3uy8kkOLmjp8yKeAimMFVBx6S06p7s2z\u000A/diBXESSlgcUPlX+BNs74B7rt1aJSglET16YDPP56AUZhtvPGdqIvWQWZqV5QTy+\u000AzjsNj1a5SvBe035qzWJp4am7zJrJDVCZ15LUCFV4jIdtFJiXeijKSujAD7YJvYPH\u000As40VVMG2Ww9PNM+5nXwTy4xQgOJhDZA4yh1fkdi51BYwD2ZVUnIaqz8MUKgoYC8n\u000A4b1PijjhAgMBAAECggEAeiQch+AwzgOKKzpqCb+fNm8XoD6ztXceSHniRKVdNN2f\u000A4UJLA1tVYD34NYJdIzW08vQJX5qLv3hjsdLncL+NE4tMVCU5SRpQLk9lYSP/Tf37\u000AdwGmzRIwuayKHQIlSi7yBkSEBgUx0VyItHwlzSjpgi2Zq9ucs5IZs9FJCyl/3fFI\u000A4o+jUKxcaaSEx6t65jJtOzRQNQUlydRhFcT3W0OxztsGq16hgrr0ii4bvd37C89e\u000AFaQadsHXy5V0EfnHKgW1CDpSDk1+akJNdkA9Nt1NbFr4VYlOFXxF8fPnyK5BELQR\u000AWzu6xeN5F9sE6QBzex7OFQGFP5OKPpqd2U1jOAG5NQKBgQDnVVefHQNRmvx50+sY\u000ANMwoOSJtfEMDFD2S6AUvO8ureii8mXAmZ8AZA0rZj/RMDkJgLXRzIAyZawwwcO5j\u000AnVSe1fstSpeOjRojtlNTpTgF3qPskCZfRcIU0Q6BHi4IfBwR+NWqcTuK8iRsmNm1\u000Aih95Ttw2kJVe0F4uVQhbP5LzdwKBgQDiFh1gduCzFzgGk371nvW/wofr0baUjmKW\u000ANDsqEbx5imJcSnxXwuMcAnsY7nzwkp7PifAxqKbZw/z3pCjq5FTIxuzu4dXD+qGC\u000AKFMP8qCszdpz7Nqg/k40oQPshEN1j9cJma0ZnDZi7X8V2UU5isEr9PRb5JZJcNtQ\u000AUhYfy1DcZwKBgGNRf6n/gdJCcU04z8F3wYMvbHmHFRo4UWtGFBvAV2QKsXyvf7ft\u000AaUsT38nihSc2JAc43LsksmQX0oblpWO9Q3xiMFG0qbb5G5TjjYjm8VOLz+MbzG2w\u000A/G+Fhe2ncGoSJtcMd2eS79ZquXqqcSYA5Bxn4CHJF2g6m4TW2xyaAdRnAoGAcZKe\u000Aa0kMk6rEUDlj+8tAtHXqhcIxr+rfB4lxdy61uXCU/LvGPuf94qI0aE/Vn5xn/uXS\u000ALYAFYTudJmHm1CijlsCnYVE9a1fKLnJHV6mQoX4/kSCYq2tUqgeAyx2eLb52TbJP\u000ATKA2ife4cadVqRRU+dnxrv/jpzz0TyMNTid6lV0CgYBV/HHEnKDqa85k2rh1xr0o\u000AMdnuwNrwLXA80tNPD3/crfN6XHuWHk1L9+Q5qKZtMA0ca8EDPhsy1ybErGC+TGvz\u000AQ21K7YPZSaPm+HZgAj4bp/qFbZlL2SAVSAqCj0w1Kr+MhB6RQkdlBjO1IErT/Btr\u000A3wbMOump+iuPwQSTNOSDLw=="
        }
      ]
    }
  },
  "ietf-netconf-server:netconf-server": {
    "listen": {
      "endpoint": [
        {
          "name": "default-ssh",
          "ssh": {
            "tcp-server-parameters": {
              "local-address": "0.0.0.0",
              "keepalives": {
                "idle-time": 1,
                "max-probes": 10,
                "probe-interval": 5
              }
            },
            "ssh-server-parameters": {
              "server-identity": {
                "host-key": [
                  {
                    "name": "default-key",
                    "public-key": {
                      "keystore-reference": "genkey"
                    }
                  }
                ]
              },
              "client-authentication": {
                "supported-authentication-methods": {
                  "publickey": [null],
                  "passsword": [null],
                  "other": [
                    "interactive"
                  ]
                },
                "users": {
                }
              }
            }
          }
        }
      ]
    }
  },
  "pdns-server:pdns-server": {
    "listen-addresses": [
      {
        "name": "global",
        "ip-address": "167.71.2.161",
        "port": 53
      },
      {
        "name": "main",
        "ip-address": "127.0.0.3"
      }
    ],
    "webserver": {
      "api-key": "secret"
    },
    "master": false,
    "slave": false
  }
}
```

Here's the program:

```cpp
#include <sysrepo-cpp/Session.hpp>

using std::cout;
using std::endl;
using std::string;

int main(int argc, char* argv[]) {
  try {
    sysrepo::S_Connection conn(new sysrepo::Connection());
    auto sess = std::make_shared<sysrepo::Session>(conn);
    cout << "switching DS to operational" << endl;
    sess->session_switch_ds(SR_DS_OPERATIONAL);
    cout << "Setting some data" << endl;
    sess->set_item_str("/pdns-server:pdns-server/listen-addresses[name='foo']/ip-address", "192.0.2.1");
    cout << "Calling validate" << endl;
    try {
      sess->validate();
      cout << "Calling apply_changes" << endl;
      sess->apply_changes();
    }
    catch (const sysrepo::sysrepo_exception& e) {
      cout << "Sysrepo error:" << endl;
      auto errors = sess->get_error();
      for (size_t i = 0; i < errors->error_cnt(); i++) {
        string xpath = errors->xpath(i) == nullptr ? "" : errors->xpath(i);
        string message = errors->message(i) == nullptr ? "" : errors->message(i);
        cout << "  xpath='" << xpath << "' message='" << message << "'" << endl;
      }
      return 1;
    }
  }
  catch (const std::exception& e) {
    cout << e.what() << endl;
    return 1;
  }
}
```

And here's the program's output:

```
root@pieter-sysrepo:~# ./pdns-sysrepo/build/load-data-in-operational
switching DS to operational
Setting some data
Calling validate
libyang[0]: Leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" of value "genkey" points to a non-existing leaf. (path: /ietf-netconf-server:netconf-server/listen/endpoint[name='default-ssh']/ssh/ssh-server-parameters/server-identity/host-key[name='default-key']/public-key/keystore-reference)
Sysrepo error:
  xpath='/ietf-netconf-server:netconf-server/listen/endpoint[name='default-ssh']/ssh/ssh-server-parameters/server-identity/host-key[name='default-key']/public-key/keystore-reference' message='Leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" of value "genkey" points to a non-existing leaf.'
  xpath='' message='Validation failed.'
```

Note that netopeer-server should be running for this. I also see this in the log from netopeer:

```
[INF]: LY: All "pdns-server" schema nodes and constraints resolved.
[INF]: LY: Module "pdns-server@2020-02-13" successfully parsed as implemented.
[INF]: LY: Module "ietf-datastores@2017-08-17" now implemented.
[INF]: SR: No scheduled changes.
[INF]: SR: Session 1456 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "genkey", but it is not required.
[INF]: LY: All data nodes and constraints resolved.
```

**Comment by michalvasko** [comment] 2020-03-20 15:30
Hi Pieter,
okay, it should work now with the latest *netopeer2*. But you will also need to reinstall `notifications` module (an internal one installed during `make install`) because there was a stray mandatory container that was causing other validation errors.

Also, it seems you are using `sr_validate()` quite a lot, which I did not really expect for some reason. I suppose it would make sense to add another optional argument `module_name` for it to allow validating only individual modules (with dependencies, naturally). That way you would not need to always validate the whole datastore. Does that make sense to you?

Regards,
Michal

**Comment by pieterlexis** [comment] 2020-03-20 17:09
> okay, it should work now with the latest netopeer2. But you will also need to reinstall notifications module (an internal one installed during make install) because there was a stray mandatory container that was causing other validation errors.

alright, after uninstalling and importing the notification model and starting netopeer2-server, it indeed works

> Also, it seems you are using sr_validate() quite a lot, which I did not really expect for some reason. I suppose it would make sense to add another optional argument module_name for it to allow validating only individual modules (with dependencies, naturally). That way you would not need to always validate the whole datastore. Does that make sense to you?

In my actual application I use it in one place. Adding a module option would be neat. I guess that decreases the load on sysrepo somewhat? Would you recommend using `sr_validate` or just use `sr_apply_changes` if I'm not doing any recovery when `sr_validate` fails?

**Comment by michalvasko** [comment] 2020-03-23 07:12
Hi,
adding module parameter to `sr_validate()` and using it would only validate the particular module data. So, you can have 2 modules A and B not depending on each other with A having 1000's of nodes and B only a few. When you then call validate on B, data of A will be ignored and not loaded/validated at all, which in this case would result in finishing it many times faster.

Generally, you do not need to call `sr_validate()` separately because everything is always validated when you apply the changes with `sr_apply_changes()`. But, it can still make sense, for example, when setting `operational` data because these are not validated automatically. Or, if you have the changes from an untrusted source (such as user input) and want to make sure they are valid before even attempting to apply them. Anyway, I will add the parameter in future, probably before the next release.

Regards,
Michal

**Comment by pieterlexis** [comment] 2020-03-25 08:25
> Generally, you do not need to call sr_validate() separately because everything is always validated when you apply the changes with sr_apply_changes(). But, it can still make sense, for example, when setting operational data because these are not validated automatically. Or, if you have the changes from an untrusted source (such as user input) and want to make sure they are valid before even attempting to apply them.

Both are actually the usecase here :-).

> Anyway, I will add the parameter in future, probably before the next release.

Awesome, much appreciated!

**Closed** 2020-05-07 11:51 UTC
