### ISSUE TITLE
Performance issue with lyp_search_file

### ISSUE THREAD

**Issue by arun11299** [CESNET/libyang#302] opened 2017-04-05 05:04 UTC
My application loads quite a lot of yang files from a directory and it was observed that the application spends more than 2 minutes to just load these yang files (~50-60 files). `strace` revealed that it was doing a lot of `stats` call in `lyp_search_file`.

I think it can be made faster by directly checking for the files presence in the current search directory and then going for other checks if the file not found.

Also, it would be nice to provide a configuration setting which would only check in the directories listed in the `search_paths` i.e it should avoid looking at deeper directories if the configuration is set.

Thanks.

**Comment by rkrejci** [comment] 2017-04-05 08:08
I'll try to do something with `stat()`, but the problem is with portability.

Going through the subdirectories was required by many users, you can always place your modules into a directory without subdirectories.

**Comment by rkrejci** [comment] 2017-04-05 08:10
btw, what do you mean by "checking for files presence"? You mean try to open it? But there are cases when you do not know the name of the file.

**Comment by rkrejci** [comment] 2017-04-05 09:12
Please try to use the `searchopt` branch - I don't see much difference with my SSD, so let me know if you will see some improvement.

**Comment by rkrejci** [comment] 2017-04-27 13:57
any feedback on this?

**Comment by arun11299** [comment] 2017-04-27 18:20
I will try to update after some tests, hopefully this weekend.

**Comment by arun11299** [comment] 2017-05-01 14:08
There is some improvement, but not much. The problem seems to be because of the `readdir` while loop to check the file existence. I guess it would be faster to just check if file is present or not in the current directory and if not, iterate through the directories.

**Comment by rkrejci** [comment] 2017-05-03 11:43
Which file? How can you know what is the filename of the module you are searching for? `readdir` is used to get all the matching names where the module can be expected. And mostly you need to go through all the names because without specified revision, libyang tries to get the newest revision.

Can you provide e.g. recorded perf data to show that searching for schema files is really the issue? Because I would expect that parsing and validating schema files should be much more time consuming than searching for files.

**Comment by rkrejci** [comment] 2017-07-07 09:08
I'm closing the issue since there is no feedback. The provided changes in the separated branch were not verified to provide any reasonable performance gain, so they were not merged into the main branches.

**Closed by rkrejci** 2017-07-07 09:08 UTC
