### ISSUE TITLE
Fail parsing some tailf yang files

### ISSUE THREAD

**Issue by OrlySch** [CESNET/libyang#241] opened 2017-01-15 09:42 UTC
Hello, 

I'm trying to connect netopeer-gui to a tailf Confd server. 
I'm having some problems parsing and loading some tailf yang files:

I got the following errors: 

(The whole log trace is also attached)
[NetopeerLog.txt](https://github.com/CESNET/libyang/files/706499/NetopeerLog.txt)

Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Invalid keyword "}".
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Module parsing failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Invalid keyword "}".
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Module parsing failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Importing "tailf-common" module into "tailf-netconf-monitoring" failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Module "tailf-netconf-monitoring" parsing failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Invalid keyword "}".
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Module parsing failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Importing "tailf-common" module into "tailf-netconf-monitoring" failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Module "tailf-netconf-monitoring" parsing failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Invalid keyword "}".
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Module parsing failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Importing "tailf-common" module into "eci-tp" failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Module "eci-tp" parsing failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Invalid keyword "}".
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Module parsing failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Importing "tailf-common" module into "eci-tp" failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Module "eci-tp" parsing failed.
Jan 12 15:57:18 ubuntu16 netopeerguid[28833]: lib ERROR: Session 12: error reply to a <get-schema> RPC (tag "invalid-value", message "/get-schema/identifier: inconsistent value").

tailf-netconf-monitoring and tailf-coomon yang files are also attached 

[tailf-netconf-monitoring.yang.txt](https://github.com/CESNET/libyang/files/706497/tailf-netconf-monitoring.yang.txt)
[tailf-common.yang.txt](https://github.com/CESNET/libyang/files/706494/tailf-common.yang.txt)

Thanks,
Orly.

**Comment by michalvasko** [comment] 2017-01-16 08:56
Hi Orly,
the error is likely caused by the use of extensions, which are not supported yet, but it is being worked on. However, libyang skips all the extensions for now when parsing schemas and this works for YIN format, but obviously not for YANG, so we will fix this. For now you can convert the schemas into YIN.

Regards,
Michal

**Comment by OrlySch** [comment] 2017-01-16 15:00
Hi Michal, 

Thanks for your fast answer!

I have converted some of the yang files to yin and its still fails to parse and load

Here is th Log

[LogAfterYinConvert.txt](https://github.com/CESNET/libyang/files/708710/LogAfterYinConvert.txt)

Thanks,
Orly.

**Comment by PavolVican** [comment] 2017-01-16 21:13
Hi Orly,
it should be fixed for YANG format. This fix is in devel branch. So far extensions are ignored. 

Regards,
Pavol

**Comment by rkrejci** [comment] 2017-01-17 07:20
Hi Pavel, is it applicable also to master? If so, please cherry pick it there.

**Closed** 2017-01-17 08:27 UTC

**Comment by PavolVican** [comment] 2017-01-17 08:28
Hi Radek. Yes, it is also in master.

**Comment by OrlySch** [comment] 2017-01-17 12:36
Hi Pavol, 

I still get errors like Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Invalid value "tailf-meta-extensions" of "include".

Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Session 21: error reply to a <get-schema> RPC (tag "invalid-value", message "/get-schema/identifier: inconsistent value").
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Session 21: error reply to a <get-schema> RPC (tag "invalid-value", message "/get-schema/identifier: inconsistent value").
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Session 21: error reply to a <get-schema> RPC (tag "invalid-value", message "/get-schema/identifier: inconsistent value").
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: User module retrieval callback failed!
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Session 21: error reply to a <get-schema> RPC (tag "invalid-value", message "/get-schema/identifier: inconsistent value").
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: User module retrieval callback failed!
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Invalid value "tailf-meta-extensions" of "include".
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Including "tailf-meta-extensions" module into "tailf-common" failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Module "tailf-common" parsing failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Importing "tailf-common" module into "tailf-kicker" failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Module "tailf-kicker" parsing failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Session 21: error reply to a <get-schema> RPC (tag "invalid-value", message "/get-schema/identifier: inconsistent value").
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: User module retrieval callback failed!
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Invalid value "tailf-meta-extensions" of "include".
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Including "tailf-meta-extensions" module into "tailf-common" failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Module "tailf-common" parsing failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Module "tailf-common" parsing failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Session 21: error reply to a <get-schema> RPC (tag "invalid-value", message "/get-schema/identifier: inconsistent value").
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: User module retrieval callback failed!
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Invalid value "tailf-meta-extensions" of "include".
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Including "tailf-meta-extensions" module into "tailf-common" failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Module "tailf-common" parsing failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Importing "tailf-common" module into "tailf-netconf-monitoring" failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Module "tailf-netconf-monitoring" parsing failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Session 21: error reply to a <get-schema> RPC (tag "invalid-value", message "/get-schema/identifier: inconsistent value").
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: User module retrieval callback failed!
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Invalid value "tailf-meta-extensions" of "include".
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Including "tailf-meta-extensions" module into "tailf-common" failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Module "tailf-common" parsing failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Importing "tailf-common" module into "eci-tp" failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Module "eci-tp" parsing failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Session 21: error reply to a <get-schema> RPC (tag "invalid-value", message "/get-schema/identifier: inconsistent value").

The whole file is 
[LogAfterUpdateBranch.txt](https://github.com/CESNET/libyang/files/710997/LogAfterUpdateBranch.txt)


Thanks,
Orly.

**Comment by michalvasko** [comment] 2017-01-17 13:24
Hi Orly,
it didn't occur to me before, but you are using submodules, which **libnetconf** cannot work with at all. You can try to use the new **netopeer2-server** (based on **libnetconf2**), but we have not tried this yet even though it should work.

Regards,
Michal

**Comment by OrlySch** [comment] 2017-01-17 14:28
Hi Michal, 
I'm using the new netopeer-gui client which is based on libnetconf2 and working with tail-f Confd server

Thanks,
Orly.

**Comment by michalvasko** [comment] 2017-01-18 08:24
Hi Orly,
you are right, my mistake. But in that case I am not sure there is any problem on our side, the error replies you see are generated by the server. Maybe it prints something additional to `inconsistent value` because I have no idea what is meant by that.

Regards,
Michal

**Comment by OrlySch** [comment] 2017-01-18 08:56
Hi Michal,

I'm more concerned with the problems related to the yang extensions.

ERROR: Invalid value "tailf-meta-extensions" of "include". 
ERROR: Including "tailf-meta-extensions" module into "tailf-common" failed.
ERROR: Module "tailf-common" parsing failed.

Thanks,
Orly.

**Comment by michalvasko** [comment] 2017-01-18 09:12
But those errors are the direct result of failed `get-schema` RPC. The submodule cannot be included if its data failed to be retrieved from the server.

Michal

**Comment by OrlySch** [comment] 2017-01-18 09:22
Hi, 

As far as I understand, it seems to overcome the server rpc errors with loading the yang files from /usr/local/share/libnetconf2/
Submodule "tailf-meta-extensions" successfully parsed, but still I get these error... 

Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib VERBOSE: Searching for "tailf-meta-extensions" in /usr/local/share/libnetconf2.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib VERBOSE: Searching for "tailf-meta-extensions" in /.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib VERBOSE: Loading schema from "/usr/local/share/libnetconf2/tailf-meta-extensions.yang" file.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib VERBOSE: Submodule "tailf-meta-extensions" successfully parsed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Invalid value "tailf-meta-extensions" of "include".
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Including "tailf-meta-extensions" module into "tailf-common" failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Invalid value "tailf-meta-extensions" of "include".
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Including "tailf-meta-extensions" module into "tailf-common" failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib VERBOSE: Searching for "tailf-meta-extensions" in /usr/local/share/libnetconf2.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib VERBOSE: Searching for "tailf-meta-extensions" in /.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib VERBOSE: Loading schema from "/usr/local/share/libnetconf2/tailf-meta-extensions.yang" file.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib VERBOSE: Submodule "tailf-meta-extensions" successfully parsed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Invalid value "tailf-meta-extensions" of "include".
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Including "tailf-meta-extensions" module into "tailf-common" failed.
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Invalid value "tailf-meta-extensions" of "include".
Jan 17 13:31:31 ubuntu16 netopeerguid[22315]: lib ERROR: Including "tailf-meta-extensions" module into "tailf-common" failed.


Thanks,
Orly.

**Comment by michalvasko** [comment] 2017-01-19 12:32
Hi Orly,
this really is strange and I failed to reproduce your issue, **netopeerguid** successfully loaded all the models. Are all the libraries recent? If they are, you will need to do some debugging yourself for me to be able to help you.

Regards,
Michal

**Comment by OrlySch** [comment] 2017-01-19 16:03
Hi Michal,

Thank you for your help!

I'm attaching the new Log after updating with recent libraries just in case..
I still see the "include extension" problem there...

[LogAfterUpdateVersion.txt](https://github.com/CESNET/libyang/files/717097/LogAfterUpdateVersion.txt)

Tell me what debugging to do :)

Thanks,
Orly.

**Comment by michalvasko** [comment] 2017-01-20 08:23
Hi Orly,
the log actually seems fine to me now, it successfully loaded all the models (just skipped all the extensions) in the end and they should be available to the client.

Regards,
Michal

**Comment by OrlySch** [comment] 2017-01-25 10:38
Hi Michal, 

Many thanks for your fast responses!

I think that it is still problematic.

I get these errors (when I press the "configure" button in the client)

Jan 25 12:16:05 ubuntu16 netopeerguid[1634]: lib ERROR: Value "$1$PWe5IPiA$6uzA0858KRf5wgrIfcDD.." does not satisfy the constraint "$0$.*|$1$[a-zA-Z0-9./]{1,8}$[a-zA-Z0-9./]{22}|$5$(rounds=\d+$)?[a-zA-Z0-9./]{1,16}$[a-zA-Z0-9./]{43}|$6$(rounds=\d+$)?[a-zA-Z0-9./]{1,16}$[a-zA-Z0-9./]{86}" (range, length, or pattern).
Jan 25 12:16:05 ubuntu16 netopeerguid[1634]: error calback: empty error list
Jan 25 12:16:05 ubuntu16 netopeerguid[1634]: lib ERROR: Failed to parse <get> reply.
Jan 25 12:16:05 ubuntu16 netopeerguid[1634]: error calback: nonempty error list


the whole log is attached
[Log2501.txt](https://github.com/CESNET/libyang/files/729288/Log2501.txt)

Thanks,
Orly.

**Comment by michalvasko** [comment] 2017-01-25 10:51
Hi Orly,
what exactly is not clear to you about this error? Somehow an invalid value is parsed by **libyang**, which displays an error describing exactly what is wrong. My guess is that the server was configured with some test value (notice `..` at the end of the value), which does not satisfy the constraint. Everything works as it should on our side.

Regards,
Michal

**Comment by OrlySch** [comment] 2017-01-26 15:32
Thanks :)
