### ISSUE TITLE
Problem with the LYD_OPT_DATA_NO_YANGLIB validation flag

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#905] opened 2019-10-17 00:13 UTC
It seems the latest libyang available on master (1.0.76) isn't honoring the `LYD_OPT_DATA_NO_YANGLIB` validation flag anymore.

Code snippet to reproduce the problem:
```c
struct lyd_node *dnode = NULL;
if (lyd_validate(&dnode, LYD_OPT_DATA | LYD_OPT_DATA_NO_YANGLIB, ly_ctx) {
        // error handling
}
```

`lyd_validate()` fails and the following error is logged:
`Missing required element "content-id" in "yang-library". (/ietf-yang-library:yang-library)`.

The same code works using libyang v0.16-r3.

Any help would be appreciated!

**Comment by michalvasko** [comment] 2019-10-17 06:04
Hi,
you will need to provide a full example because I did not reproduce it with the snippet.

Regards,
Michal

**Comment by rwestphal** [comment] 2019-10-18 02:45
@michalvasko sure, here's a full program that can be used to reproduce the issue:

```c
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <err.h>

#include <libyang/libyang.h>

int main(int argc, char **argv)
{
        struct ly_ctx *ly_ctx;
        struct lyd_node *dnode;

        ly_ctx = ly_ctx_new("/usr/local/share/yang/", 0);
        if (!ly_ctx)
                errx(1, "ly_ctx_new()");

        if (ly_ctx_load_module(ly_ctx, "frr-isisd", NULL) == NULL)
                errx(1, "ly_ctx_load_module(): %s", ly_errmsg(ly_ctx));

        dnode = NULL;
        if (lyd_validate(&dnode, LYD_OPT_DATA | LYD_OPT_DATA_NO_YANGLIB, ly_ctx)
            != 0)
                errx(1, "lyd_validate(): %s", ly_errmsg(ly_ctx));

        lyd_free_withsiblings(dnode);
        ly_ctx_destroy(ly_ctx, NULL);

        return 0;
}
```

frr-isisd.yang: https://raw.githubusercontent.com/FRRouting/frr/master/yang/frr-isisd.yang

Thanks in advance!

**Comment by michalvasko** [comment] 2019-10-18 06:10
Hi Renato,
nope, your example still works fine for me. I have tested on my OpenSUSE Tumbleweed and Ubuntu 14.04 with *libyang* 1.0.76.

Regards,
Michal

**Comment by rwestphal** [comment] 2019-10-18 13:52
That's interesting!

I did a bisect and noticed that problem was introduced between 1.0.69 and 1.0.70 (commit df6ec7bd1189651e3f202e70f43aaea830ebe851 to be more precise). Reverting that commit fixed the problem for me. I'll try to provide more information later.

FWIW, I'm using Debian 10 here (and gcc 8.3.0).

**Comment by michalvasko** [comment] 2019-10-18 13:57
I see, then you have probably found a specific module setup where it does not work. That commit changes how internal modules are retrieved from the context, so that what I would focus on. I doubt I can help you more because I am not likely to reproduce this.

Regards,
Michal

**Comment by rwestphal** [comment] 2019-10-18 14:10
So, removing the ietf-inet-types.yang module (Revision 2019-07-21) from `/usr/local/share/yang/` fixed the problem for me (no idea how it ended up there).

**Comment by michalvasko** [comment] 2019-10-21 06:31
Hi Renato,
I could reproduce it and it should be fixed, thanks.

Regards,
Michal

**Closed** 2019-10-21 06:31 UTC
