### ISSUE TITLE
Error in operational datastore update : Failed to find matching hash for a child

### ISSUE THREAD

**Issue by meghna-doshi** [CESNET/libyang#1763] opened 2022-01-05 20:09 UTC
Hi,
We are getting some error like : 
ERROR ""SR Syslog"" Failed to find matching hash for a child of ""restricted-interfaces" 

(sometimes it comes for restricted-interfaces and sometimes we are getting for some other nodes)
We are not able to reproduce so cannot give exact scenario but following is high level what we are doing:
1. Operational datastore update to create a list entry.
2. Operational datastore update to delete the entry created in 1.
3. Operational datastore update to create list entry again.

We wanted to understand what does this error mean? Can you please give any inputs here, would be very helpful for us to debug this further.
I cannot share yang files since those are proprietary ones. Will try to create some sample yang files if we understand what scenario is causing this issue.

sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v1.4.147 (SO v5.6.63)
./local/lib64/libyang.so.1.10.32

**Comment by meghna-doshi** [comment] 2022-01-06 20:05
Hi Michal,
Thanks for the response. Can you be more clear on the above explaination. I see that this error is coming from lyb_parse_schema_hash (). So what exactly is this function checking? 
Is it checking the xpath that the application has sent for operational DB update with the yang schema?

**Comment by meghna-doshi** [comment] 2022-01-07 06:48
Hi Michal,
we have one more observation related to this.

We have code like:

try
{
    m_OperationalDBSession->apply_changes (...);
    printf ("apply success");
}
catch( const std::exception& e )
{
    printf ( "apply_changes failed");
}

where:
m_OperationalDBSession = std::make_shared<sysrepo::Session>(conn,SR_DS_OPERATIONAL);

So looks there is error in apply_changes but we are getting error log two times? Any idea why and how apply_changes is giving error two times.

ERROR "SR Syslog" Failed to find matching hash for a child of "ru-instance".
ERROR "SR Syslog" Failed to find matching hash for a child of "ru-instance".

apply_changes failed
apply_changes failed

**Comment by michalvasko** [comment] 2022-01-07 07:20
Fine then, if you think the details will be of any help to you. Like I said, it is all about the LYB YANG data format. Every data node's schema node is stored in the form of a hash. These hashes are calculated for all the siblings on one level in the schema because the information about level is also stored in LYB. So, what this error says is: I have parsed `ru-instance` data node and a now parsing all its children. I am determining the schema node of each child by reading its stored hash and comparing it to the hashes of all the schema children of the schema node `ru-instance`. But no match is found, hence the error.

Like I said, the reason why no hash matches may vary so I would strongly suggest just trying to find a reproducer test case and leaving the fix to me, the LYB format is not exactly simple.

**Comment by meghna-doshi** [comment] 2022-01-07 07:47
Thanks Michal, yes we are also trying to reproduce but not able to get much success. So was checking if the logic can help us understand.
Thanks.
Anything on that try-catch why 2 times error is getting logged.

**Comment by michalvasko** [comment] 2022-01-07 07:55
> Anything on that try-catch why 2 times error is getting logged.

It is irrelevant, the LYB file is simply being parsed twice, I cannot tell you why exactly.

**Comment by meghna-doshi** [comment] 2022-01-11 05:44
Hi Michal,
This issue is happening intermittently, but is there anything which we can collect from live to help debug this issue.
Still not able to reproduce with exact steps, so not able to give much info.
But our observation is that this is happening due to some race condition getting hit when operational datastore update and running datastore updates happen simultaneously.

Is there any locking we might have to do during operational datastore update, when running datastore is being accessed by NETCONF client? is there any prescribed sysrepo lock API which we have to call to handle such situations?

**Comment by michalvasko** [comment] 2022-01-11 07:48
Concurrent write to the LYB file would explain why it gets corrupted afterwards but there should be locks preventing this, used automatically. But it is possible there is a problem and that it was fixed in version 2 so like I said, my suggestion is to migrate to the newer version. Operational data are handled differently so there is a good chance you will not encounter this problem anymore.

**Closed** 2022-05-31 09:55 UTC
Labels: is:bug, libyang1
