### ISSUE TITLE
validate union with leafref fails

### ISSUE THREAD

**Issue by kwatsen** [CESNET/libyang#1944] opened 2022-11-22 18:00 UTC
Using latest `devel` branch:
```
% yanglint --version
yanglint 2.0.211
```

With this YANG:
```
module test {
  yang-version 1.1;
  namespace "test";
  prefix "test";

  list leafref-target {
    key id;
    leaf id {
      type string;
    }
  }
  leaf leafref-leaf {
    //type union {   <--  this line uncommented later
      type leafref {
        path "/leafref-target/id";
      }
    //}   <-- this line uncommented later
  }
}
```

And this JSON:
```
{
  "test:leafref-target": [ {"id":"tgt1"} ],
  "test:leafref-leaf": "baz"
}   
```

Validation correctly fails:
```
% yanglint test.yang test.json
libyang err : Invalid leafref value "baz" - no target instance "/leafref-target/id" with the same value. (Schema location /test:leafref-leaf, data location /test:leafref-leaf, line number 4.)
YANGLINT[E]: Failed to parse input data file "test.json".
```

However, uncommenting the two lines, validation INCORRECTLY succeeds:
```
% yanglint test.yang test.json
% echo $?
0
```

**Comment by michalvasko** [comment] 2022-11-23 07:00
Duplicate of #1927, fixed in the latest release.

**Closed by michalvasko** 2022-11-23 07:00 UTC
