### ISSUE TITLE
lyht_insert_with_resize_cb segmentfault

### ISSUE THREAD

**Issue by lumanyu180** [CESNET/libyang#967] opened 2019-12-04 03:37 UTC
Hi,

I compiled libyang for debug target，then it assert at func : lyht_find_collision, assert(empty); it is called by lyht_insert_with_resize_cb not in for cycle。it is called by function : lyht_insert_with_resize_cb in line 644 (code is the master branch).
I check the memory of the hash table。It is as follow:
used = 4, size = 8, rec_size = 16, recs=0x7fffa400c4e0. And the 8 ht_rec informations is : 
the hash value is : 1684542317, 805673277, 1684542317, 2648011995,805673277, 200102157,509474286,509474286.  The idx  ( idx = hash & (ht->size - 1)) of every ht_rec is : 5, 5, 5, 3, 5, 5, 6, 6. And the hits of every ht_rec is : -1, -1, -1, 1, 1, 2, 1, -1。When the failed assert occurs, func lyht_find_collision first is : 0x7fffa400c530. It's idx is 5, and hits is 2。*last is also 0x7fffa400c530 . In fact *last has been changed by function lyht_find_collision。I think it is because first is just after its collisions, its collision's address 0x7fffa400c520，whose idx is 5, and hits is 1. So when enter function lyht_find_collision, *last is 0x7fffa400c520, and then i = 4, then
i = (i + 1) % ht->size; so i is 5, then lyht_get_rec(ht->recs, ht->rec_size, i) return 0x7fffa400c530, which is just equall first（0x7fffa400c530）， so the assert failed。I think  *last address should after  first address，but it is not.   Thanks for your reply.

**Comment by michalvasko** [comment] 2019-12-04 08:16
Duplicate of #963.

**Closed by michalvasko** 2019-12-04 08:16 UTC
