### ISSUE TITLE
"key" and "unique" of "list" not filtering duplicate data nodes

### ISSUE THREAD

**Issue by KC-Su** [CESNET/libyang#260] opened 2017-02-07 10:42 UTC
Hi, 
I found that libyang(still 11.105 version) can't filter the duplicate data nodes automatically when parsing json file neither by using "key" and "unique".

Here are my yang and json:
```Yang
module schema {
  yang-version 1.1;
  prefix 'schema';

  list list-example {
    key "person_id";
    unique "name";
    leaf name {
        type string;
    }
    leaf person_id {
        type int32;
    } 
  }
}
```
```json
{
    "schema:list-example": [
        {
            "name": "Amy",
            "person_id": 10001
        },
        {
            "name": "Amy",
            "person_id": 10001
        }
    ]
}
```

Data tree creates two same data nodes, but schema nodes are no problem (have unique bit set and keys array with right information).
Since all needed information prepared, I guess filtering operation is assumed to be done by user?

thanks for paying attention.

Best.

**Comment by michalvasko** [comment] 2017-02-07 11:08
Hi,

if creating a new issue, please always use the most recent version of a library in either `master` or `devel` branch. I tried your example with libyang 0.11.109 and it behaved exactly as expected (both key value and unique value were checked). Nevertheless, I see no relevant changes from 0.11.105 that could have affected this, so please provide the steps you used to parse or create/validate the data and the unexpected result you got, thanks.

Regards,
Michal

**Comment by KC-Su** [comment] 2017-02-08 02:20
Hi, 

First I have to apologize about using older version, next time I will ask with newest `master` branch.
Sorry about that.

Actually yesterday I just provide partial yang and json, because I think rest of it would not affect result, but in fact it does,  apologize again...my fault. :( 

Here is the whole yang and json file:
``` yang
module schema {

  yang-version 1.1;
  namespace "http://www.example.com/yang/schema";
 
  prefix 'schema';

  container temp_cont {
    leaf leaf_temp {
        type string;
    }
  }

  feature feature_A;

  container top_container {
    //when "2>3";
    //must "2>3";
    //presence "exsiting is significant";
    //config false;
    //status "obsolete";
    //if-feature "feature_A";
    leaf leaf-A {
      type int32;
    }
  }

  leaf leaf-B {
    //when "2>3";
    //must "2>1";
    //default 1;
    //config false;
    //mandatory true;
    //status "obsolete";
    //if-feature "feature_A";
    type int32;
  }

  leaf-list leaflist-A {
    //when "2>3";
    //must "2>3";
    //if-feature "feature_A";
    //default "default string 1";
    //default "default string 2";
    //config false;
    //status "obsolete";
    //ordered-by user;
    //min-elements 1;
    //max-elements 1;
    type string;
  }

  list list-A {
    //when "2>1";
    key "company_id";
    unique name;
    leaf name {
        type string;
    }
    leaf company_id {
        type int32;
    } 
  }
}
```
```json
{
    "schema:temp_cont": {
        "leaf_temp": "not meaning"
    },
    "schema:top_container": {
        "leaf-A": 9487
    },
    "schema:leaf-B": 9487,
    "schema:leaflist-A": [
        "first string",
        "second string"
    ],
    "schema:list-A": [
        {
            "name": "Amy",
            "company_id": 10001
        },
        {
            "name": "Amy",
            "company_id": 10001
        }
    ]
}
```
C code and gdb information at breakpoint of line `if (xpath_result == NULL)`:
```c
int main()
{
	int i;
	struct ly_ctx* context = NULL;
	const struct ly_set *xpath_result = NULL;
	const struct lyd_node *data = NULL;
	const struct lys_module *module = NULL;

	context = ly_ctx_new("./");
	if (context == NULL) {
		printf("ly_ctx_new faield!\n");
	}
	
	module 	= ly_ctx_load_module(context, "schema", NULL);

    if (module == NULL) {
        printf("ly_ctx_laod_module failed!\n");
        return 1;
    }

    //lys_features_enable(module, "feature_A");

	data = lyd_parse_path(context, "./data.json", LYD_JSON, LYD_OPT_CONFIG);
	if (data == NULL) {
		printf("lyd_parse_path failed!\n");
	    return 1;
    }

    xpath_result = lyd_find_xpath(data, "/schema:list-A");
    if (xpath_result == NULL) {
    	printf("lyd_find_xpath failed!\n");
    } else {
    	printf("find %d data node\n", xpath_result->number);
    }

    return 1;
}
```
```
(gdb) p xpath_result->number
$1 = 2
(gdb) p xpath_result->set.d[0]->schema->name
$2 = 0x60f070 "list-A"
(gdb) p xpath_result->set.d[1]->schema->name
$3 = 0x60f070 "list-A"
(gdb) p ((const struct lyd_node_leaf_list*)xpath_result->set.d[0]->child)->value->int32
$4 = 10001
(gdb) p ((const struct lyd_node_leaf_list*)xpath_result->set.d[1]->child)->value->int32
$5 = 10001
(gdb) p ((const struct lyd_node_leaf_list*)xpath_result->set.d[0]->child->next)->value_str
$6 = 0x608240 "Amy"
(gdb) p ((const struct lyd_node_leaf_list*)xpath_result->set.d[1]->child->next)->value_str
$7 = 0x608240 "Amy"
```
Seems two data nodes with same memory address are linked.  
I tried different yang and json files this time I give and yesterday I gave, the issue will meet just with the files of this time, but I can't find out what's wrong with my yang and json...

Anyway thanks for your patience.

Best.

**Comment by michalvasko** [comment] 2017-02-08 08:42
Hi,

firstly, it's fine, just please remember what I wrote for any next issues. Regarding the issue, I managed to reproduce it in the `master` branch, but it worked exactly as expected in the `devel` branch. The reason will likely be partial validation refactorization. Since the changes were quite extensive, the fix would not be easily merged into `master`, so you will have to wait until full merge, which should happen at the end of February. Or use the `devel` branch, sorry.

Regards,
Michal

**Closed by michalvasko** 2017-02-08 08:42 UTC
