### ISSUE TITLE
When path issue for Cisco-IOS-XR-config-cfgmgr-exec-oper?

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libyang#176] opened 2016-10-28 23:31 UTC
When trying to add the module [Cisco-IOS-XR-config-cfgmgr-exec-oper@2015-11-09.yang](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/611/Cisco-IOS-XR-config-cfgmgr-exec-oper.yang) in `yanglint`, I'm seeing below error.

```
./yanglint 
> add Cisco-IOS-XR-config-cfgmgr-exec-oper@2015-11-09.yang
libyang[0]: Schema node "type" not found (../type). (path: /Cisco-IOS-XR-config-cfgmgr-exec-oper:cfg-hist-gl/record-type/record/info/a)
libyang[0]: Module "Cisco-IOS-XR-config-cfgmgr-exec-oper" parsing failed.
```

The when statement looks ok to me:

```
leaf a {
      xr:xr-xml-map "shcfghistory:a";
      when "../type != 'cfghist-bag-record-alarm' and ../type !="+
        " 'cfghist-bag-record-cfs-check' and ../type !="+
        " 'cfghist-bag-record-commit' and ../type !="+
        " 'cfghist-bag-record-oir' and ../type !="+
        " 'cfghist-bag-record-shutdown' and ../type !="+
        " 'cfghist-bag-record-startup' and ../type !="+
        " 'cfghist-bag-record-backup'" {
          description
            "../type != 'CFGHIST_BAG_RECORD_ALARM' and .
            ./type != 'CFGHIST_BAG_RECORD_CFSCHECK' and .
            ./type != 'CFGHIST_BAG_RECORD_COMMIT' and .
            ./type != 'CFGHIST_BAG_RECORD_OIR' and ../type
            != 'CFGHIST_BAG_RECORD_SHUTDOWN' and ../type 
            != 'CFGHIST_BAG_RECORD_STARTUP' and ../type !=
            'CFGHIST_BAG_RECORD_BACKUP'";
      }
```

The tree for this model looks like below:

```
module: Cisco-IOS-XR-config-cfgmgr-exec-oper
   +--ro cfg-hist-gl
      +--ro record-type* [record-type]
         +--ro record-type    xr:Cisco-ios-xr-string
         +--ro record* [record]
            +--ro record         int32
            +--ro info
            ...
            |  +--ro type?            Hist-record
            |  +--ro a?               uint32
```

Any idea why this model is not being accepted by `yanglint`?

**Comment by rkrejci** [comment] 2016-10-31 13:28
The issue is fixed in devel branch. Or at least I'm not able to reproduce the issue with the current devel branch.

**Closed by rkrejci** 2016-10-31 13:28 UTC
