### ISSUE TITLE
Module "ietf-yang-library" parsing failed 

### ISSUE THREAD

**Issue by fabioantonini1969** [CESNET/libyang#148] opened 2016-10-11 03:44 UTC
Hi
I have downloaded libyang 0.10.210 and now I have problem to parse ietf-yang-library. For instance yanglint fails to start with the following traces.
Of course any other application using libyang fails to start with the same problem

~ # yanglint
libyang[2]: Reading module "yang".
libyang[2]: Module "yang" successfully parsed.
libyang[2]: Reading module "ietf-inet-types".
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
libyang[2]: All "ietf-inet-types" schema nodes and constraints resolved.
libyang[2]: Module "ietf-inet-types" successfully parsed.
libyang[2]: Reading module "ietf-yang-types".
libyang[2]: Module "ietf-yang-types" successfully parsed.
libyang[2]: Reading module "ietf-yang-library".
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[2]: Resolving uses "schema-leaf" failed, it will be attempted later.
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[2]: Resolving uses "schema-leaf" failed, it will be attempted later.
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[2]: Resolving uses "module-list" failed, it will be attempted later.
libyang[2]: Resolving "ietf-yang-library" unresolved schema nodes and their constraints...
libyang[0]: Module "ietf-yang-library" parsing failed.
Failed to create context.

What's happening?
The problem occurs also with 0.10.211 downloaded this morning.
It doesn't occur with the 0.9.186
What am I missing?
Thanks a lot
fabio

**Comment by fabioantonini1969** [comment] 2016-10-11 03:49
it can be tagged as "Question"

**Comment by fabioantonini1969** [comment] 2016-10-11 04:19
Just for your information I'm cross-compiling libyang for a MIPS target.  Not a x86 platform.

**Comment by fabioantonini1969** [comment] 2016-10-11 04:39
I have some more verbose traces (ly_verb(LY_LLDBG))

libyang[2]: Reading module "ietf-yang-library".
libyang[3]: DICT: inserting (refcount) "urn:ietf:params:xml:ns:yang:ietf-yang-library"
libyang[3]: DICT: inserting (refcount) "yanglib"
libyang[3]: DICT: inserting (refcount) "IETF NETCONF (Network Configuration) Working Group"
libyang[3]: DICT: inserting (refcount) "WG Web:   <https://datatracker.ietf.org/wg/netconf/>
WG List:  <mailto:netconf@ietf.org>

WG Chair: Mehmet Ersue
          <mailto:mehmet.ersue@nsn.com>

WG Chair: Mahesh Jethanandani
          <mailto:mjethanandani@gmail.com>

Editor:   Andy Bierman
          <mailto:andy@yumaworks.com>

Editor:   Martin Bjorklund
          <mailto:mbj@tail-f.com>

Editor:   Kent Watsen
          <mailto:kwatsen@juniper.net>"
libyang[3]: DICT: inserting (refcount) "This module contains monitoring information about the YANG
modules and submodules that are used within a YANG-based
server.

Copyright (c) 2016 IETF Trust and the persons identified as
authors of the code.  All rights reserved.

Redistribution and use in source and binary forms, with or
without modification, is permitted pursuant to, and subject
to the license terms contained in, the Simplified BSD License
set forth in Section 4.c of the IETF Trust's Legal Provisions
Relating to IETF Documents
(http://trustee.ietf.org/license-info).

This version of this YANG module is part of RFC 7895; see
the RFC itself for full legal notices."
libyang[3]: DICT: inserting (refcount) "yang"
libyang[3]: DICT: inserting (refcount) "inet"
libyang[3]: DICT: inserting (refcount) "Initial revision."
libyang[3]: DICT: inserting (refcount) "RFC 7895: YANG Module Library."
libyang[3]: DICT: inserting (refcount) "revision-identifier"
libyang[3]: DICT: inserting (refcount) "Represents a specific date in YYYY-MM-DD format."
libyang[3]: DICT: inserting (refcount) "string"
libyang[3]: DICT: inserting "\d{4}-\d{2}-\d{2}"
libyang[3]: DICT: inserting (refcount) "module-list"
libyang[3]: DICT: inserting (refcount) "The module data structure is represented as a grouping
so it can be reused in configuration or another monitoring
data structure."
libyang[3]: YIN: parsing grouping statement "module-list"
libyang[3]: DICT: inserting (refcount) "common-leafs"
libyang[3]: DICT: inserting (refcount) "Common parameters for YANG modules and submodules."
libyang[3]: YIN: parsing grouping statement "common-leafs"
libyang[3]: DICT: inserting (refcount) "name"
libyang[3]: DICT: inserting (refcount) "The YANG module or submodule name."
libyang[3]: YIN: parsing leaf statement "name"
libyang[3]: DICT: inserting "ietf-yang-types:yang-identifier"
libyang[3]: DICT: inserting (refcount) "ietf-yang-types"
libyang[3]: DICT: inserting (refcount) "revision"
libyang[3]: DICT: inserting (refcount) "The YANG module or submodule revision date.
A zero-length string is used if no revision statement
is present in the YANG module or submodule."
libyang[3]: YIN: parsing leaf statement "revision"
libyang[3]: DICT: inserting (refcount) "union"
libyang[3]: DICT: inserting (refcount) "revision-identifier"
libyang[3]: DICT: inserting (refcount) "string"
libyang[3]: DICT: inserting (refcount) "0"
libyang[3]: DICT: inserting (refcount) "schema-leaf"
libyang[3]: DICT: inserting (refcount) "Common schema leaf parameter for modules and submodules."
libyang[3]: YIN: parsing grouping statement "schema-leaf"
libyang[3]: DICT: inserting (refcount) "schema"
libyang[3]: DICT: inserting (refcount) "Contains a URL that represents the YANG schema
resource for this module or submodule.

This leaf will only be present if there is a URL
available for retrieval of the schema for this entry."
libyang[3]: YIN: parsing leaf statement "schema"
libyang[3]: DICT: inserting "ietf-inet-types:uri"
libyang[3]: DICT: inserting (refcount) "ietf-inet-types"
libyang[3]: DICT: inserting (refcount) "module"
libyang[3]: DICT: inserting (refcount) "Each entry represents one revision of one module
currently supported by the server."
libyang[3]: YIN: parsing list statement "module"
libyang[3]: DICT: inserting (refcount) "common-leafs"
libyang[3]: YIN: parsing uses statement "common-leafs"
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[3]: DICT: inserting (refcount) "schema-leaf"
libyang[3]: YIN: parsing uses statement "schema-leaf"
libyang[2]: Resolving uses "schema-leaf" failed, it will be attempted later.
libyang[3]: DICT: inserting (refcount) "namespace"
libyang[3]: DICT: inserting (refcount) "The XML namespace identifier for this module."
libyang[3]: YIN: parsing leaf statement "namespace"
libyang[3]: DICT: inserting "ietf-inet-types:uri"
libyang[3]: DICT: inserting (refcount) "ietf-inet-types"
libyang[3]: DICT: inserting (refcount) "feature"
libyang[3]: DICT: inserting (refcount) "List of YANG feature names from this module that are
supported by the server, regardless of whether they are
defined in the module or any included submodule."
libyang[3]: YIN: parsing leaf-list statement "feature"
libyang[3]: DICT: inserting "ietf-yang-types:yang-identifier"
libyang[3]: DICT: inserting (refcount) "ietf-yang-types"
libyang[3]: DICT: inserting (refcount) "deviation"
libyang[3]: DICT: inserting (refcount) "List of YANG deviation module names and revisions
used by this server to modify the conformance of
the module associated with this entry.  Note that
the same module can be used for deviations for
multiple modules, so the same entry MAY appear
within multiple 'module' entries.

The deviation module MUST be present in the 'module'
list, with the same name and revision values.
The 'conformance-type' value will be 'implement' for
the deviation module."
libyang[3]: YIN: parsing list statement "deviation"
libyang[3]: DICT: inserting (refcount) "common-leafs"
libyang[3]: YIN: parsing uses statement "common-leafs"
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[3]: DICT: inserting (refcount) "name revision"
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[3]: DICT: inserting (refcount) "conformance-type"
libyang[3]: DICT: inserting (refcount) "Indicates the type of conformance the server is claiming
for the YANG module identified by this entry."
libyang[3]: YIN: parsing leaf statement "conformance-type"
libyang[3]: DICT: inserting (refcount) "enumeration"
libyang[3]: DICT: inserting (refcount) "implement"
libyang[3]: DICT: inserting (refcount) "Indicates that the server implements one or more
protocol-accessible objects defined in the YANG module
identified in this entry.  This includes deviation
statements defined in the module.

For YANG version 1.1 modules, there is at most one
module entry with conformance type 'implement' for a
particular module name, since YANG 1.1 requires that,
at most, one revision of a module is implemented.

For YANG version 1 modules, there SHOULD NOT be more
than one module entry for a particular module name."
libyang[3]: DICT: inserting (refcount) "import"
libyang[3]: DICT: inserting (refcount) "Indicates that the server imports reusable definitions
from the specified revision of the module but does
not implement any protocol-accessible objects from
this revision.

Multiple module entries for the same module name MAY
exist.  This can occur if multiple modules import the
same module but specify different revision dates in
the import statements."
libyang[3]: DICT: inserting (refcount) "submodule"
libyang[3]: DICT: inserting (refcount) "Each entry represents one submodule within the
parent module."
libyang[3]: YIN: parsing list statement "submodule"
libyang[3]: DICT: inserting (refcount) "common-leafs"
libyang[3]: YIN: parsing uses statement "common-leafs"
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[3]: DICT: inserting (refcount) "schema-leaf"
libyang[3]: YIN: parsing uses statement "schema-leaf"
libyang[2]: Resolving uses "schema-leaf" failed, it will be attempted later.
libyang[3]: DICT: inserting (refcount) "name revision"
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[3]: DICT: inserting (refcount) "name revision"
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[3]: DICT: inserting (refcount) "modules-state"
libyang[3]: DICT: inserting (refcount) "Contains YANG module monitoring information."
libyang[3]: YIN: parsing container statement "modules-state"
libyang[3]: DICT: inserting (refcount) "module-set-id"
libyang[3]: DICT: inserting (refcount) "Contains a server-specific identifier representing
the current set of modules and submodules.  The
server MUST change the value of this leaf if the
information represented by the 'module' list instances
has changed."
libyang[3]: YIN: parsing leaf statement "module-set-id"
libyang[3]: DICT: inserting (refcount) "string"
libyang[3]: DICT: inserting (refcount) "module-list"
libyang[3]: YIN: parsing uses statement "module-list"
libyang[2]: Resolving uses "module-list" failed, it will be attempted later.
libyang[3]: DICT: inserting (refcount) "yang-library-change"
libyang[3]: DICT: inserting (refcount) "Generated when the set of modules and submodules supported
by the server has changed."
libyang[3]: YIN: parsing notification statement "yang-library-change"
libyang[3]: DICT: inserting (refcount) "module-set-id"
libyang[3]: DICT: inserting (refcount) "Contains the module-set-id value representing the
set of modules and submodules supported at the server at
the time the notification is generated."
libyang[3]: YIN: parsing leaf statement "module-set-id"
libyang[3]: DICT: inserting (refcount) "leafref"
libyang[3]: DICT: inserting "/ietf-yang-library:modules-state/ietf-yang-library:module-set-id" with collision 
libyang[2]: Resolving "ietf-yang-library" unresolved schema nodes and their constraints...
libyang[0]: Module "ietf-yang-library" parsing failed.
Failed to create context.

hope this can help

**Comment by fabioantonini1969** [comment] 2016-10-11 05:15
Now I have tried the version 0.9.186 and it works

**Comment by michalvasko** [comment] 2016-10-11 11:30
Hi,
it's really difficult for us to help you if you're not using x86. Unfortunately, there is no relevant information in the debug output you provided, which is strange in itself. Are you able to do some debugging yourself (using `gdb` for example)?

Regards,
Michal

**Comment by fabioantonini** [comment] 2016-10-11 12:04
Hi Michal
Thanks a lot for your feedback
It's strange that with the previous version 0.9.186 everything worked as a charm.
I don't apply any custom patch. Just compile with my cross-compiler for MIPS. So I cannot believe that this is an endianess problem. I'll try to do by myself. thanks 
fabio

**Comment by fabioantonini** [comment] 2016-10-11 12:11
just a last comment about some output strings
is it normal to have such a kind of output?

libyang[3]: DICT: inserting "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\p{N}\p{L}]+)?" with collision

thanks
fabio

**Comment by michalvasko** [comment] 2016-10-11 12:32
Hi Fabio,
you are right, the first character is obviously some invalid character value, it should not be there, so you can start you debugging there.

Regards,
Michal

**Comment by fabioantonini** [comment] 2016-10-11 14:07
does this new version depend on a specific release of pcre?
I cannot understand what's the problem. The compiler is always the same. One week ago the libyang.so worked fine. I have just updated the libyang release. So something has changed in the source code.
I don't modify anything in the source code for MIPS porting.
regards
fabio

**Comment by michalvasko** [comment] 2016-10-11 14:12
Hi Fabio,
no, required PCRE version remained the same, but there are lots of changes, we support YANG 1.1 now. But something is obviusly wrong in the patterns being added into the dictionary, try to solve that problem first.

Regards,
Michal

**Comment by fabioantonini1969** [comment] 2016-10-12 04:22
Hi Michal
just to let me to be aligned with you, which is the libpcre version are you using?
thanks 
fabio

**Comment by rkrejci** [comment] 2016-10-12 07:31
I don't think that libpcre is problem, I would focus on that odd byte in this string:
```
libyang[3]: DICT: inserting "�\d{4}-\d{2}-\d{2}"
```

I plan to look at that on 32b system, on 64b everything looks fine, neither the source file contains that byte, so it must be something in parsing XML. There are some changes in 0.10 connected with more strict rules in YANG 1.1, but it should be just about checking, not about parsing. I will see later today.

**Comment by fabioantonini** [comment] 2016-10-12 07:47
Hi Radek
thanks a lot for your support
my processor is a 32b system (embedded mips cpu). Feel free to ask more details about my platform if you need. At the moment I had to go back to the previous running version (0.9.186) and also for sysrepo/netopeer2. Anyway I should move to the newest release of all packages as soon as this problem will be focused.
regards
fabio

**Comment by rkrejci** [comment] 2016-10-12 09:03
Hi, I'm not able to reproduce it on 32b i386. Could you try to compile and run it in your environment with the modified libyang's `parser.c` and yanglint's main.c? It adds a lot of debug messages. Please run the compiled `yanglint`:
```
$ ./yanglint 2> log
```
and provide the log (github allows you to attach file to the comment).

[modifiedsources.zip](https://github.com/CESNET/libyang/files/523971/modifiedsources.zip)

**Comment by fabioantonini** [comment] 2016-10-12 11:12
Hi Radek
but what debug level is
ly_verb(5)
in libyang.h I read
typedef enum {
    LY_LLSILENT = -1, /**< Print no messages. */
    LY_LLERR = 0,     /**< Print only error messages, default value. */
    LY_LLWRN,         /**< Print error and warning messages. */
    LY_LLVRB,         /**< Besides errors and warnings, print some other verbose messages. */
    LY_LLDBG          /**< Print all messages including some development debug messages. */
} LY_LOG_LEVEL;

Anyway running the modified yanglint with the modified libyang.so.0.10.216 I get the following output

~ # cat log 
libyang[2]: Reading module "yang".
libyang[2]: Module "yang" successfully parsed.
libyang[2]: Reading module "ietf-inet-types".
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
libyang[2]: All "ietf-inet-types" schema nodes and constraints resolved.
libyang[2]: Module "ietf-inet-types" successfully parsed.
libyang[2]: Reading module "ietf-yang-types".
libyang[2]: Module "ietf-yang-types" successfully parsed.
libyang[2]: Reading module "ietf-yang-library".
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[2]: Resolving uses "schema-leaf" failed, it will be attempted later.
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[2]: Resolving uses "schema-leaf" failed, it will be attempted later.
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[2]: Resolving uses "module-list" failed, it will be attempted later.
libyang[2]: Resolving "ietf-yang-library" unresolved schema nodes and their constraints...
libyang[0]: Module "ietf-yang-library" parsing failed.
Failed to create context.
regards
fabio

p.s. my cpu architecture is big endian. Could be this the problem?

**Comment by fabioantonini** [comment] 2016-10-12 12:11
Replacing LOGDBG with nomal print I get a more verbose output
please find it in attach
[log.radek.txt](https://github.com/CESNET/libyang/files/524329/log.radek.txt)

**Comment by rkrejci** [comment] 2016-10-12 18:15
`ly_verb(5)` is just setting log level high to print all messages, using `LY_LLDBG` should have the same effect as `5` or `10` or anything `>=3`. The log is not very useful, because I see just part of the messages - I need a combination of the new messages with the `libyang[3]: DICT` messages you posted in the earlier comment.

**Comment by rkrejci** [comment] 2016-10-12 18:18
ad endianity, in general, yes - I will need to change the code slightly. But in this particular case, I don't thing so. According to the log.radek.txt you have provided, all characters are 1-byte, so endianity shouldn't be important here.

**Comment by fabioantonini1969** [comment] 2016-10-12 18:30
Hi Radek
thanks  a lot...I'm arriving with more logs ...

**Comment by fabioantonini1969** [comment] 2016-10-12 19:09
Unfortunately if I use your modified sources I get only the logs here below.

./yanglint 
libyang[2]: Reading module "yang".
libyang[2]: Module "yang" successfully parsed.
libyang[2]: Reading module "ietf-inet-types".
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
libyang[2]: All "ietf-inet-types" schema nodes and constraints resolved.
libyang[2]: Module "ietf-inet-types" successfully parsed.
libyang[2]: Reading module "ietf-yang-types".
libyang[2]: Module "ietf-yang-types" successfully parsed.
libyang[2]: Reading module "ietf-yang-library".
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[2]: Resolving uses "schema-leaf" failed, it will be attempted later.
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[2]: Resolving uses "common-leafs" failed, it will be attempted later.
libyang[2]: Resolving uses "schema-leaf" failed, it will be attempted later.
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[2]: Resolving list keys "name revision" failed, it will be attempted later.
libyang[2]: Resolving uses "module-list" failed, it will be attempted later.
libyang[2]: Resolving "ietf-yang-library" unresolved schema nodes and their constraints...
libyang[0]: Module "ietf-yang-library" parsing failed.
Failed to create context.

I have the same output on a x86 platform (using ly_verb(LY_LLDBG))

./yanglint 
libyang[2]: Reading module "yang".
libyang[2]: Module "yang" successfully parsed.
libyang[2]: Reading module "ietf-inet-types".
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
libyang[2]: All "ietf-inet-types" schema nodes and constraints resolved.
libyang[2]: Module "ietf-inet-types" successfully parsed.
libyang[2]: Reading module "ietf-yang-types".
libyang[2]: Module "ietf-yang-types" successfully parsed.
libyang[2]: Reading module "ietf-yang-library".
libyang[2]: Module "ietf-yang-library" successfully parsed.
>

I can guess that the log verbosity is overwritten somewhere in the new library

**Comment by fabioantonini** [comment] 2016-10-12 19:13
Radek here in attach the log traces using ly_verb(LY_LLDBG) for the previous library version (0.9.186)
it could be useful when we can compare the logs of the failing case

[log.0.9.186.txt](https://github.com/CESNET/libyang/files/525421/log.0.9.186.txt)

thanks
fabio

**Comment by rkrejci** [comment] 2016-10-13 08:00
debug messages are hidden when the library is compiled in `Release` mode. Please make sure that libyang is compiled in default `Debug` mode (see README for more info).

The log from previous version shows that there is no odd byte at the beginning of the pattern strings.

**Comment by fabioantonini** [comment] 2016-10-13 08:29
Hi Radek
here the required logs
[log.radek.debug.txt](https://github.com/CESNET/libyang/files/526556/log.radek.debug.txt)
thanks

**Comment by rkrejci** [comment] 2016-10-13 12:49
I have 2 observations from the last log:
- there are no odd bytes in pattern strings, so it seems that it was caused just by copying output from terminal, data seems fine when reading XML
- next issue is that uses are not resolved even the target groupings are already defined and should be easily found. Here it seems as endianity issue, but before fixing it I want to ask you to compile and run the attached code, and post the output. I don't have a test environment for that and it should help me to get know what exactly is happening with the bit fields on big-endian platform in our case.

[endianity.c.txt](https://github.com/CESNET/libyang/files/527109/endianity.c.txt)

**Comment by fabioantonini** [comment] 2016-10-13 12:52
Hi Radek
feel free to ask me every test you need. I'll compile and return back the output
Thanks so much

**Comment by fabioantonini** [comment] 2016-10-13 12:54
here the output

~ # ./endianity 
Sizes: a: 2 b: 2 c: 2 d: 2
1    : a.x:     1 b.x:     1 c.x:     1 d.x:     1
1    : a.y:     0 b.y:     0 c.y:     0 d.y:     0
1    : a.z:     4 b.z:   256 c.z:     1 d.z:     1
1    : a.0:     0 b.0:     1 c.0:     0 d.0:     0
1    : a.1:     4 b.1:     0 c.1:     1 d.1:     1
--------------------------------------------------
2    : a.x:     2 b.x:     2 c.x:     2 d.x:     2
2    : a.y:     0 b.y:     0 c.y:     0 d.y:     0
2    : a.z:     8 b.z:   512 c.z:     2 d.z:     2
2    : a.0:     0 b.0:     2 c.0:     0 d.0:     0
2    : a.1:     8 b.1:     0 c.1:     2 d.1:     2
--------------------------------------------------
4    : a.x:     4 b.x:     4 c.x:     4 d.x:     4
4    : a.y:     0 b.y:     0 c.y:     0 d.y:     0
4    : a.z:    16 b.z:  1024 c.z:     4 d.z:     4
4    : a.0:     0 b.0:     4 c.0:     0 d.0:     0
4    : a.1:    16 b.1:     0 c.1:     4 d.1:     4
--------------------------------------------------
8    : a.x:     8 b.x:     8 c.x:     8 d.x:     8
8    : a.y:     0 b.y:     0 c.y:     0 d.y:     0
8    : a.z:    32 b.z:  2048 c.z:     8 d.z:     8
8    : a.0:     0 b.0:     8 c.0:     0 d.0:     0
8    : a.1:    32 b.1:     0 c.1:     8 d.1:     8
--------------------------------------------------
16   : a.x:    16 b.x:    16 c.x:    16 d.x:    16
16   : a.y:     0 b.y:     0 c.y:     0 d.y:     0
16   : a.z:    64 b.z:  4096 c.z:    16 d.z:    16
16   : a.0:     0 b.0:    16 c.0:     0 d.0:     0
16   : a.1:    64 b.1:     0 c.1:    16 d.1:    16
--------------------------------------------------
32   : a.x:    32 b.x:    32 c.x:    32 d.x:    32
32   : a.y:     0 b.y:     0 c.y:     0 d.y:     0
32   : a.z:   128 b.z:  8192 c.z:    32 d.z:    32
32   : a.0:     0 b.0:    32 c.0:     0 d.0:     0
32   : a.1:   128 b.1:     0 c.1:    32 d.1:    32
--------------------------------------------------
64   : a.x:    64 b.x:    64 c.x:    64 d.x:    64
64   : a.y:     0 b.y:     0 c.y:     0 d.y:     0
64   : a.z:   256 b.z: 16384 c.z:    64 d.z:    64
64   : a.0:     1 b.0:    64 c.0:     0 d.0:     0
64   : a.1:     0 b.1:     0 c.1:    64 d.1:    64
--------------------------------------------------
128  : a.x:   128 b.x:   128 c.x:   128 d.x:   128
128  : a.y:     0 b.y:     0 c.y:     0 d.y:     0
128  : a.z:   512 b.z: 32768 c.z:   128 d.z:   128
128  : a.0:     2 b.0:   128 c.0:     0 d.0:     0
128  : a.1:     0 b.1:     0 c.1:   128 d.1:   128
--------------------------------------------------
256  : a.x:   256 b.x:     0 c.x:   256 d.x:     0
256  : a.y:     0 b.y:     0 c.y:     0 d.y:     0
256  : a.z:  1024 b.z:     0 c.z:   256 d.z:     0
256  : a.0:     4 b.0:     0 c.0:     1 d.0:     0
256  : a.1:     0 b.1:     0 c.1:     0 d.1:     0
--------------------------------------------------
512  : a.x:   512 b.x:     0 c.x:   512 d.x:     0
512  : a.y:     0 b.y:     0 c.y:     0 d.y:     0
512  : a.z:  2048 b.z:     0 c.z:   512 d.z:     0
512  : a.0:     8 b.0:     0 c.0:     2 d.0:     0
512  : a.1:     0 b.1:     0 c.1:     0 d.1:     0
--------------------------------------------------
1024 : a.x:  1024 b.x:     0 c.x:  1024 d.x:     0
1024 : a.y:     0 b.y:     0 c.y:     0 d.y:     0
1024 : a.z:  4096 b.z:     0 c.z:  1024 d.z:     0
1024 : a.0:    16 b.0:     0 c.0:     4 d.0:     0
1024 : a.1:     0 b.1:     0 c.1:     0 d.1:     0
--------------------------------------------------
2048 : a.x:  2048 b.x:     0 c.x:  2048 d.x:     0
2048 : a.y:     0 b.y:     0 c.y:     0 d.y:     0
2048 : a.z:  8192 b.z:     0 c.z:  2048 d.z:     0
2048 : a.0:    32 b.0:     0 c.0:     8 d.0:     0
2048 : a.1:     0 b.1:     0 c.1:     0 d.1:     0
--------------------------------------------------
4096 : a.x:  4096 b.x:     0 c.x:  4096 d.x:     0
4096 : a.y:     0 b.y:     0 c.y:     0 d.y:     0
4096 : a.z: 16384 b.z:     0 c.z:  4096 d.z:     0
4096 : a.0:    64 b.0:     0 c.0:    16 d.0:     0
4096 : a.1:     0 b.1:     0 c.1:     0 d.1:     0
--------------------------------------------------
8192 : a.x:  8192 b.x:     0 c.x:  8192 d.x:     0
8192 : a.y:     0 b.y:     0 c.y:     0 d.y:     0
8192 : a.z: 32768 b.z:     0 c.z:  8192 d.z:     0
8192 : a.0:   128 b.0:     0 c.0:    32 d.0:     0
8192 : a.1:     0 b.1:     0 c.1:     0 d.1:     0
--------------------------------------------------

**Comment by fabioantonini** [comment] 2016-10-13 12:55
as a txt file 
[endianity.txt](https://github.com/CESNET/libyang/files/527122/endianity.txt)

**Comment by rkrejci** [comment] 2016-10-13 13:30
Thanks Fabio, there is new branch `bigendian` - please try to pull, compile and run yanglint to get know if the fix works.

**Comment by fabioantonini** [comment] 2016-10-13 13:33
I'll keep you informed...thanks a lot for your time

**Comment by fabioantonini** [comment] 2016-10-13 13:46
Great news!! it works!!!
thanks a lot
~ # /usr/lib/yanglint 
libyang[2]: Reading module "yang".
libyang[2]: Module "yang" successfully parsed.
libyang[2]: Reading module "ietf-inet-types".
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving derived type "union" failed, it will be attempted later.
libyang[2]: Resolving type default "(null)" failed, it will be attempted later.
libyang[2]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
libyang[2]: All "ietf-inet-types" schema nodes and constraints resolved.
libyang[2]: Module "ietf-inet-types" successfully parsed.
libyang[2]: Reading module "ietf-yang-types".
libyang[2]: Module "ietf-yang-types" successfully parsed.
libyang[2]: Reading module "ietf-yang-library".
libyang[2]: Module "ietf-yang-library" successfully parsed.

There are some fails about 'union' but I guess that are not blocking. Is it right?
Thanks a lot. In my opinion the issue can be closed
fabio

**Comment by rkrejci** [comment] 2016-10-13 13:57
That should be ok, sometime it is not possible to resolve everything on the first attempt, but the mentioned things are then resolved between
```
libyang[2]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
libyang[2]: All "ietf-inet-types" schema nodes and constraints resolved.
```

Anyway, the messages does not seem correct (`"(null)" shouldn't be there), so I will check it. But that is just a minor issue, and parsed schema should be ok. I will merge the `bigendian` branch into master which will close this issue.

Thanks for cooperation

**Comment by fabioantonini** [comment] 2016-10-13 13:59
Thanks a lot for your valuable support

**Closed** 2016-10-13 14:18 UTC
