### ISSUE TITLE
Getting unexpected logs - possible bug

### ISSUE THREAD

**Issue by steweg** [CESNET/libyang#2239] opened 2024-05-20 14:56 UTC
Hi, I am getting logs like this:
```
Annotation definition for attribute \\"yang:lyds_tree\\" not found.: Data path: ...
````
As I am using context with just built-in plugins, lyds_tree plugin is never loaded and as such the call will always fail. 

As I am not calling any public API, which works with metadata, I guess it is triggered from somewhere internally. Any idea, what can actually cause this? Thanks

**Comment by michalvasko** [comment] 2024-05-21 06:19
Right, this plugin should always be loaded because it is needed (only) internally. Should be fixed.

**Comment by steweg** [comment] 2024-05-21 11:31
I tried your fix, but the problem still persist

**Comment by michalvasko** [comment] 2024-05-21 11:32
Then please provide simple steps to reproduce it.

**Comment by steweg** [comment] 2024-05-21 13:39
I am not able to easily reproduce it as I don't have C code, which uses just those basic plugins. My app in mainly in python. So what I did was to introduce arbitrary segfault error into the code, right before place where the log is being generated and this is the backtrace from gdb:
```
[Switching to Thread 0x7ffff43ce640 (LWP 97285)]
0x00007ffff47caafb in lyd_create_meta (parent=0x7fffec264260, meta=0x7ffff43c9868, mod=0x7fffec23a240, name=0x7ffff48fc310 "lyds_tree", name_len=9, value=0x0, value_len=0, is_utf8=0 '\000', store_only=1 '\001', dynamic=0x0, format=LY_VALUE_CANON, prefix_data=0x0, hints=1011, ctx_node=0x0, clear_dflt=0 '\000', incomplete=0x0) at /root/libyang/src/tree_data.c:1362
1362            printf("%s\n", ant_type->name);
(gdb) backtrace
#0  0x00007ffff47caafb in lyd_create_meta (parent=0x7fffec264260, meta=0x7ffff43c9868, mod=0x7fffec23a240, name=0x7ffff48fc310 "lyds_tree", name_len=9, value=0x0, value_len=0,
    is_utf8=0 '\000', store_only=1 '\001', dynamic=0x0, format=LY_VALUE_CANON, prefix_data=0x0, hints=1011, ctx_node=0x0, clear_dflt=0 '\000', incomplete=0x0)
    at /root/libyang/src/tree_data.c:1362
#1  0x00007ffff482b2c7 in lyds_create_metadata (leader=0x7fffec264260, meta_p=0x7ffff43c98d8) at /root/libyang/src/tree_data_sorted.c:1180
#2  0x00007ffff482b4c7 in lyds_insert (first_sibling=0x7ffff43c9928, leader=0x7ffff43c9930, node=0x7fffec26cf00) at /root/libyang/src/tree_data_sorted.c:1237
#3  0x00007ffff47c89e8 in lyd_insert_node (parent=0x7fffec258d50, first_sibling_p=0x7fffec258d88, node=0x7fffec26cf00, order=0) at /root/libyang/src/tree_data.c:764
#4  0x00007ffff47ebb07 in lydjson_maintain_children (parent=0x7fffec258d50, first_p=0x7fffec258d88, node_p=0x7ffff43c99f0, last=0 '\000', ext=0x0) at /root/libyang/src/parser_json.c:935
#5  0x00007ffff47ee3cc in lydjson_subtree_r (lydctx=0x7fffec26d290, parent=0x7fffec258d50, first_p=0x7fffec258d88, parsed=0x0) at /root/libyang/src/parser_json.c:1750
#6  0x00007ffff47ecfc0 in lydjson_parse_instance_inner (lydctx=0x7fffec26d290, snode=0x7fffec26a240, ext=0x0, status=0x7ffff43c9bd4, node=0x7ffff43c9c10)
    at /root/libyang/src/parser_json.c:1425
#7  0x00007ffff47ed591 in lydjson_parse_instance (lydctx=0x7fffec26d290, parent=0x0, first_p=0x7fffec2572e0, snode=0x7fffec26a240, ext=0x0,
    name=0x7fffec271267 "schemas\": [{\"id\": \"65cbc876-c9f7-4cae-9641-78612931364b\", \"version\": \"v1.0.1\", \"modules\": [{\"id\": \"537facbb-538b-44c7-a325-a67a4b8effe7\", \"name\": \"sde2e-customer-network-cfs\", \"filePath\": \"data/schema"..., name_len=7,
    prefix=0x7fffec271262 "main:schemas\": [{\"id\": \"65cbc876-c9f7-4cae-9641-78612931364b\", \"version\": \"v1.0.1\", \"modules\": [{\"id\": \"537facbb-538b-44c7-a325-a67a4b8effe7\", \"name\": \"sde2e-customer-network-cfs\", \"filePath\": \"data/s"..., prefix_len=4, status=0x7ffff43c9bd4, node=0x7ffff43c9c10) at /root/libyang/src/parser_json.c:1523
#8  0x00007ffff47ee30d in lydjson_subtree_r (lydctx=0x7fffec26d290, parent=0x0, first_p=0x7fffec2572e0, parsed=0x7ffff43c9dc0) at /root/libyang/src/parser_json.c:1743
#9  0x00007ffff47ee949 in lyd_parse_json (ctx=0x7fffec1f2f70, ext=0x0, parent=0x0, first_p=0x7fffec2572e0, in=0x7fffec254150, parse_opts=100728832, val_opts=0, int_opts=32,
    parsed=0x7ffff43c9dc0, subtree_sibling=0x7ffff43c9d9f "", lydctx_p=0x7ffff43c9db0) at /root/libyang/src/parser_json.c:1881
#10 0x00007ffff47c6793 in lyd_parse (ctx=0x7fffec1f2f70, ext=0x0, parent=0x0, first_p=0x7fffec2572e0, in=0x7fffec254150, format=LYD_JSON, parse_opts=100728832, val_opts=0, op=0x0)
    at /root/libyang/src/tree_data.c:132
#11 0x00007ffff47c6db1 in lyd_parse_data (ctx=0x7fffec1f2f70, parent=0x0, in=0x7fffec254150, format=LYD_JSON, parse_options=100728832, validate_options=0, tree=0x7fffec2572e0)
    at /root/libyang/src/tree_data.c:222
#12 0x00007ffff5ca7c6b in _cffi_f_lyd_parse_data (self=<optimized out>, args=<optimized out>) at build/temp.linux-x86_64-cpython-310/_libyang.c:6204
#13 0x00005555556ae138 in ?? ()
#14 0x00005555556a4a7b in _PyObject_MakeTpCall ()
<---skipping rest of python backtrace--->
```

But when I shifted `plugins_metadata` into the list plugins that will always load, everything worked with no problems. So I guess `lyds_tree` plugin requires also `metadata` plugin for proper working.

Hope it helps you identify the correct way how to fix it.

**Comment by michalvasko** [comment] 2024-05-21 13:56
Yes, thanks for the hint, those are required as well.

**Closed** 2024-05-21 16:14 UTC
Labels: is:bug, status:completed
