### ISSUE TITLE
Deviation of local module is not supported

### ISSUE THREAD

**Issue by robshakir** [CESNET/libyang#1080] opened 2020-05-07 05:30 UTC
Tested Versions:
* `yanglint 0.16.105`
* `yanglint SO 1.7.10` (`devel`@ `0599d13c142854215139580ba778ff2cbd23eb53`)

yanglint today states that a module cannot deviate its own contents. I didn't see this as something that's listed in RFC7950, or RFC6020. This pattern is used in some modules - such as OpenConfig - generally as a way to be able to re-use a grouping from another module but remove a subset of the grouping. This pattern is supported by other toolchains (pyang, goyang).

This issue was found as a part of an expansion in our compatibility checking pipeline for OpenConfig, led by @wenovus. 

Minimum reproducible module:

```yang
module deviate-self {
	prefix "t";
	namespace "urn:t";

	container a {
		container b {
			leaf c { type string; }
			leaf d { type string; }
		}
	}

	deviation "/a/b/c" { deviate not-supported; }
}
```

`yanglint` output:

```
root@628efa18400b:~/yanglintbugs# yanglint deviate-self.yang 
err : Invalid value "/a/b/c" of "deviation".
err : Deviating own module is not allowed.
err : Module "deviate-self" parsing failed.
```

Please let us know if there are additional outputs we can provide.

**Comment by michalvasko** [comment] 2020-05-07 06:39
Hi,
yes, the current *libyang* (up to version 1.x) does not support this and will not. However, the new *libyang* version 2 already supports this and we plan to have it ready for a release in several months.

Nevertheless, the [YANG 1.1 RFC](https://tools.ietf.org/html/rfc7950#section-7.20.3) states the purpose of deviations quite clearly and for modules compliant with this it really makes no sense to deviate themselves.

Regards,
Michal

**Comment by robshakir** [comment] 2020-05-07 13:59
In both this case and #1081, I simplified down the modules for ease of reproducing the bug and adding test coverage. The use case is for deviation of functionality -- particularly:

* There is some module `openconfig-interfaces` that provides a generic interfaces structure.
* There is some other context `openconfig-access-points` which describes WiFi access points, it turns out some features defined in `openconfig-interfaces` (a small number) aren't applicable to access-points.
* `openconfig-access-points` defines its own structure, since the context it has is >1 different physical device - it therefore `uses` a grouping from `openconfig-interfaces` in its own context.
* To remove features from this structure used from `openconfig-interfaces` (i.e., deviate another module's contents) it needs a `deviation` statement, however, since there was a `uses` of the grouping then the other module's contents are actually in this local modules' context.

Now, are there other ways to achieve this? For sure -- one could split up the other module's `grouping` to the most granular possible sets of groupings and replicate the structure under the `openconfig-access-points` module -- however, this is a lot of duplication, and means that there isn't automatic fixing of issues across both modules, thus the approach above seems the best. You can't `refine` to remove nodes.

YANG itself is overly flexible and expressive -- it has a lot of different nuances like this -- and as a tool author I can completely get the pushback on "this isn't something that seems reasonable". We've actually gone to the extent in OpenConfig of trying to cut down the features that we allow in modules, such that we can limit the complexity of the different functionality we have to rely on. However, I think there's a choice to be made as to whether the tooling is intended to support YANG's usage in general vs. support a specific set of 'approved' modules. I'd note that due to the restrictions above, OC is one of the lower-feature sets of YANG modules.

That being said -- thanks for having this fixed in libyang 2.x. Where this will leave us is that we'll likely just have to point out that anything that relies on libyang 1.x is incompatible with OpenConfig based on this feature gap. Luckily, it's for a subset of modules -- but there isn't a clear fix otherwise.

Thanks for the reply,
r.

**Comment by michalvasko** [comment] 2020-05-07 14:09
Hi,
like you said, YANG is overly flexible so I am quite sure there would be a reasonable solution without the use of deviations, but we do not have to agree on this, it will make no difference. As for OpenConfig not being compatible with libyang 1.x that is actually already the case because of the infamous `oc-ext:regexp-posix` extension that changes the meaning of all the patterns. Any module that uses it and defines a pattern will be interpreted as standard YANG pattern meaning not as intended. However, this problem will likely persist for libyang 2.x as well because the extensions are currently implemented in the same way and they simply do not allow changing meanings of standard statements.

Regards,
Michal

**Closed** 2022-05-31 09:25 UTC
