### ISSUE TITLE
How to know if a node is a key node

### ISSUE THREAD

**Issue by masif-cs** [CESNET/libyang#1107] opened 2020-06-10 06:06 UTC
Hi

Is there any way(api or attribute in structure like lys_node) I can know if a node is a key node or not?
Just like in below XPATH, id is key.
**XPATH:**
_3gpp-common-managed-element:ManagedElement[id='1']/_3gpp-nr-nrm-gnbcucpfunction:GNBCUCPFunction[id='1']/_3gpp-nr-nrm-nrcellcu:NRCellCU[id='1']/attributes/priorityLabel

**XML Looks like below for above XPATH:**
<?xml version="1.0"?>
```
<ManagedElement xmlns="urn:3gpp:sa5:_3gpp-common-managed-element">
  <id>1</id>
  <GNBCUCPFunction xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-gnbcucpfunction">
    <id>1</id>
    <NRCellCU xmlns="urn:3gpp:sa5:_3gpp-nr-nrm-nrcellcu">
      <id>1</id>
      <attributes>
        <priorityLabel>200</priorityLabel>
      </attributes>
    </NRCellCU>
  </GNBCUCPFunction>
</ManagedElement>
```

**Comment by michalvasko** [comment] 2020-06-10 11:38
Hi,
you can use [lys_is_key](https://netopeer.liberouter.org/doc/libyang/master/group__schematree.html#ga111ba82b0d48b2e6ca609d7b709797d4), for example.

Regards,
Michal

**Comment by michalvasko** [comment] 2020-06-11 06:19
Hi,
generally it seems fine but what exactly are you trying to achieve? Print the augments definitions or the applied augment nodes in the tree? Also note that this way you are typing everything to `struct lys_node` but augments are `struct lys_node_augment` and this structure does not have `name`.

Regards,
Michal

**Comment by masif-cs** [comment] 2020-08-14 19:12
Hi @michalvasko ,

One problem I am facing related to the api(**lys_is_key**) you asked me to use for checking whether a node is a key node or not. For some keys I see that it doesnt work. Can you please have a look. PFA yang model for which I am seeing the issue. The List for which I am seeing the problem is low-level-tx-endpoints, Line 1145 of the attached yang.

```
list low-level-tx-endpoints {
      key "name";

      description
        "Object model for low-level-tx-endpoints configuration - augmented static-low-level-tx-endpoints by local-address
        which cannot be added to static low-level-tx-endpoints as we cannot have modificable element in static object";

      leaf name {
        type leafref {
          path "/user-plane-configuration/static-low-level-tx-endpoints/name";
          require-instance false;
        }
        mandatory true;

        description
          "Unique name of low-level-tx-endpoint object. Reference to static object";
      }

```
[o-ran-uplane-conf.zip](https://github.com/CESNET/libyang/files/5076682/o-ran-uplane-conf.zip)

**Comment by michalvasko** [comment] 2020-08-17 06:32
Duplicate of #1171.

**Closed by michalvasko** 2020-08-17 06:32 UTC
