### ISSUE TITLE
Missing "notifications" schema in the context

### ISSUE THREAD

**Issue by PramodKAvvaru** [CESNET/libyang#1911] opened 2022-08-24 20:29 UTC
If the "ietf-datastores" module version loaded at the client doesn't match with the server version, then the "notifications" schema is getting lost from the context. 

I have tried with libyang v2.0.231 as well as devel branch, and the issue is reproducible. Logs from the netopeer2-cli copied below.

> connect --host 10.120.8.96 --login root
root@10.120.8.96 password:
ly ERROR: Loading "ietf-origin" module failed.
ly ERROR: Parsing module "ietf-netconf-nmda" failed.
ly ERROR: Module "ietf-netconf@2011-06-01" is already implemented in revision "2013-09-29".
ly ERROR: Module "ietf-datastores@2017-08-17" is already implemented in revision "2018-02-14".
> subscribe --stream NETCONF
nc ERROR: Missing "notifications" schema in the context.
cli_send_recv: Failed to send the RPC.

by adding debug prints in libyang, I can see the "notifications" schema was known in the context until ietf-datastores warning message and after that, the "notifications" schema was missing from the context.

If I load the server with the same version of "ietf-datastores" used in client, then I don't see "notifications" missing in the context error.

I am fairly new to the libyang code. Can someone please suggest how to go about debugging this issue.

Thanks in advance!

**Comment by michalvasko** [comment] 2022-08-25 11:06
Before connecting run `verb verbose` and then you will see more output.

**Comment by PramodKAvvaru** [comment] 2022-08-26 09:25
logs collected using verb set to verbose level.

vagrant@debian-jessie:/vagrant/libyang/build$ netopeer2-cli
> verb 2
> connect --host 10.120.8.96 --login root
nc VERBOSE: Trying to connect via IPv4 to 10.120.8.96:830.
nc VERBOSE: Successfully connected to 10.120.8.96:830 over IPv4.
[2022/08/25 12:57:21.769220, 2] ssh_config_parse_line:  Unapplicable option: SendEnv, line: 51
[2022/08/25 12:57:21.769249, 2] ssh_config_parse_line:  Unsupported option: HashKnownHosts, line: 52
[2022/08/25 12:57:21.769280, 2] ssh_connect:  libssh 0.10.0 (c) 2003-2022 Aris Adamantiadis, Andreas Schneider and
 libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights,
using threading threads_pthread
[2022/08/25 12:57:21.769301, 2] ssh_connect:  Socket connecting, now waiting for the callbacks to work
[2022/08/25 12:57:21.769327, 1] socket_callback_connected:  Socket connection callback: 1 (0)
[2022/08/25 12:57:21.777202, 2] ssh_client_connection_callback:  SSH server banner: SSH-2.0-libssh_0.9.4
[2022/08/25 12:57:21.777389, 2] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh_0.9.4
[2022/08/25 12:57:21.778304, 1] ssh_known_hosts_read_entries:  Failed to open the known_hosts file '/etc/ssh/ssh_k
nown_hosts': No such file or directory
[2022/08/25 12:57:21.778623, 2] ssh_kex_select_methods:  Negotiated curve25519-sha256,rsa-sha2-512,aes256-gcm@open
ssh.com,aes256-gcm@openssh.com,aead-gcm,aead-gcm,none,none,,
[2022/08/25 12:57:21.787729, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2022/08/25 12:57:21.787996, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2022/08/25 12:57:21.788362, 2] ssh_packet_client_curve25519_reply:  SSH_MSG_NEWKEYS sent
[2022/08/25 12:57:21.789538, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[2022/08/25 12:57:21.790461, 2] ssh_packet_newkeys:  Signature verified and valid
[2022/08/25 12:57:21.791739, 1] ssh_packet_userauth_failure:  Access denied for 'none'. Authentication that can co
ntinue: publickey,keyboard-interactive,password
[2022/08/25 12:57:21.792093, 2] ssh_packet_userauth_failure:  Access denied for 'none'. Authentication that can co
ntinue: publickey,keyboard-interactive,password
nc VERBOSE: Publickey athentication.
nc VERBOSE: No key pair specified.
nc WARNING: Authentication denied.
nc VERBOSE: Password authentication (host "10.120.8.96", user "root").
root@10.120.8.96 password:
nc VERBOSE: Authentication successful.
[2022/08/25 12:57:24.924355, 2] channel_open:  Creating a channel 43 with 64000 window and 32768 max packet
[2022/08/25 12:57:24.924972, 2] ssh_packet_channel_open_conf:  Received a CHANNEL_OPEN_CONFIRMATION for channel 43
:43
[2022/08/25 12:57:24.925162, 2] ssh_packet_channel_open_conf:  Remote window : 32000, maxpacket : 35000
[2022/08/25 12:57:24.925849, 2] channel_request:  Channel request subsystem success
ly VERBOSE: Searching for "ietf-inet-types" in "/vagrant/libyang/build".
ly VERBOSE: Newer revision than "ietf-inet-types@2013-07-15" not found, using this as the latest revision.
ly VERBOSE: Searching for "ietf-yang-types" in "/vagrant/libyang/build".
ly VERBOSE: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[2022/08/25 12:57:24.948301, 2] grow_window:  growing window (channel 43:43) to 1280000 bytes
nc VERBOSE: Capability for <get-schema> support found.
nc VERBOSE: Capability for yang-library support found.
nc VERBOSE: Retrieving data for schema "ietf-netconf", revision "<latest>".
nc VERBOSE: Reading schema from localfile "/usr/share/yang/modules/netopeer2/ietf-netconf@2013-09-29.yang".
nc VERBOSE: Retrieving data for import schema "ietf-netconf-acm", revision "2018-02-14".
nc VERBOSE: Reading schema from localfile "/usr/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang".
nc VERBOSE: Retrieving data for import schema "ietf-yang-metadata", revision "2016-08-05".
nc VERBOSE: Reading schema from localfile "/usr/share/yang/modules/libyang/ietf-yang-metadata@2016-08-05.yang".
nc VERBOSE: Retrieving data for schema "ietf-yang-library", revision "2019-01-04".
nc VERBOSE: Reading schema from localfile "/usr/share/yang/modules/libyang/ietf-yang-library@2019-01-04.yang".
nc VERBOSE: Unable to identify revision of the import schema "ietf-datastores" from the available server side info
rmation.
nc VERBOSE: Retrieving data for import schema "ietf-datastores", revision "<latest>".
nc VERBOSE: Reading schema from server via get-schema.
[2022/08/25 12:57:24.969306, 2] channel_rcv_change_window:  Adding 1248206 bytes to channel (43:43) (from 31782 by
tes)
nc VERBOSE: Retrieving data for schema "ietf-netconf-nmda", revision "<latest>".
nc VERBOSE: Reading schema from localfile "/usr/share/yang/modules/netopeer2/ietf-netconf-nmda@2019-01-07.yang".
nc VERBOSE: Unable to identify revision of the import schema "ietf-origin" from the available server side informat
ion.
nc VERBOSE: Retrieving data for import schema "ietf-origin", revision "<latest>".
nc VERBOSE: Reading schema from server via get-schema.
nc WARNING: Received an unexpected reply to <get-schema>.
ly ERROR: Loading "ietf-origin" module failed.
ly ERROR: Parsing module "ietf-netconf-nmda" failed.
nc VERBOSE: Support for <get-data> from ietf-netconf-nmda not found.
nc VERBOSE: Retrieving data for schema "yang", revision "2017-02-20".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "ietf-netconf", revision "2011-06-01".
nc VERBOSE: Reading schema from server via get-schema.
ly ERROR: Module "ietf-netconf@2011-06-01" is already implemented in revision "2013-09-29".
nc WARNING: Failed to load schema "ietf-netconf@2011-06-01".
nc VERBOSE: Retrieving data for schema "ietf-netconf-notifications", revision "2012-02-06".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: **Retrieving data for schema "notifications", revision "2008-07-14".**
nc VERBOSE: **Reading schema from localfile "/usr/share/yang/modules/netopeer2/notifications@2008-07-14.yang".**
nc VERBOSE: Retrieving data for schema "nc-notifications", revision "2008-07-14".
nc VERBOSE: Reading schema from localfile "/usr/share/yang/modules/netopeer2/nc-notifications@2008-07-14.yang".
nc VERBOSE: Retrieving data for schema "ietf-x509-cert-to-name", revision "2014-12-10".
nc VERBOSE: Reading schema from localfile "/usr/share/yang/modules/netopeer2/ietf-x509-cert-to-name@2014-12-10.yan
g".
nc VERBOSE: Retrieving data for schema "ietf-keystore", revision "2016-10-31".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "ietf-netconf-with-defaults", revision "2011-06-01".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "ietf-datastores", revision "2017-08-17".
nc VERBOSE: Reading schema from server via get-schema.
ly ERROR: Module "ietf-datastores@2017-08-17" is already implemented in revision "2018-02-14".
nc WARNING: Failed to load schema "ietf-datastores@2017-08-17".
nc VERBOSE: Retrieving data for schema "ietf-netconf-server", revision "2016-11-02".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for import schema "ietf-x509-cert-to-name", revision "2014-12-10".
nc VERBOSE: Reading schema from localfile "/usr/share/yang/modules/netopeer2/ietf-x509-cert-to-name@2014-12-10.yan
g".
nc VERBOSE: Retrieving data for import schema "ietf-ssh-server", revision "2016-11-02".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for import schema "ietf-keystore", revision "2016-10-31".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for import schema "ietf-tls-server", revision "2016-11-02".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "ietf-system", revision "2014-08-06".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for import schema "iana-crypt-hash", revision "2014-08-06".
nc VERBOSE: Reading schema from localfile "/usr/share/yang/modules/netopeer2/iana-crypt-hash@2014-08-06.yang".
nc VERBOSE: Retrieving data for schema "iana-hardware", revision "2018-03-13".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "ietf-interfaces", revision "2018-02-20".
nc VERBOSE: Reading schema from localfile "/usr/share/yang/modules/netopeer2/ietf-interfaces@2018-02-20.yang".
nc VERBOSE: Retrieving data for schema "iana-if-type", revision "2017-01-19".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "ietf-crypto-types", revision "2019-04-29".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "ietf-dhcpv6-types", revision "2018-01-30".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "ietf-hardware", revision "2018-03-13".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "ietf-ip", revision "2018-02-22".
nc VERBOSE: Reading schema from localfile "/usr/share/yang/modules/netopeer2/ietf-ip@2018-02-22.yang".
nc VERBOSE: Retrieving data for schema "ietf-restconf-monitoring", revision "2017-01-26".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-ald-port", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-ald", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-antenna-calibration", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-interfaces", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-processing-element", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-compression-factors", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-module-cap", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-uplane-conf", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-beamforming", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-delay-management", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-dhcp", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-ecpri-delay", revision "2019-02-04".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-externalio", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-fan", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-file-management", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-fm", revision "2019-02-04".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-hardware", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-laa-operations", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-laa", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-lbm", revision "2019-02-04".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-mplane-int", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-operations", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-performance-management", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-software-management", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-supervision", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-sync", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-trace", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-transceiver", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
[2022/08/25 12:57:25.885464, 2] grow_window:  growing window (channel 43:43) to 1280000 bytes
nc VERBOSE: Retrieving data for schema "o-ran-troubleshooting", revision "2019-02-04".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-udp-echo", revision "2019-02-04".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "o-ran-usermgmt", revision "2019-07-03".
nc VERBOSE: Reading schema from server via get-schema.
ly VERBOSE: Missing explicit "deprecated" status specified in parent "subnet", inheriting for "prefix-length".
ly VERBOSE: Missing explicit "deprecated" status specified in parent "subnet", inheriting for "netmask".
nc WARNING: Some models failed to be loaded, any data from these models (and any other unknown) will be ignored.
> subscribe --stream NETCONF
nc ERROR: **Missing "notifications" schema in the context.**
cli_send_recv: Failed to send the RPC.
>

**Comment by michalvasko** [comment] 2022-08-26 09:55
Please try again with the latest *libnetconf2*, the messages should be better. Nevertheless, I would need to reproduce the problem locally to fix it and that may be quite a problem.

**Comment by PramodKAvvaru** [comment] 2022-08-30 12:34
Thanks @michalvasko. I have tried with latest libnetconf2 code from devel branch and found issue still exists. logs below. I am continuing with my debugging and will post if any findings.

```
nc VERBOSE: Retrieving data for schema "ietf-netconf-notifications", revision "2012-02-06".
nc VERBOSE: Reading schema from server via get-schema.
nc VERBOSE: Retrieving data for schema "notifications", revision "2008-07-14".
> subscribe --stream NETCONF
nc ERROR: Missing "notifications" schema in the context.
cli_send_recv: Failed to send the RPC.
```

Complete logs attached.
[connect_libnetconf2_devel.log](https://github.com/CESNET/libyang/files/9452765/connect_libnetconf2_devel.log)

**Comment by PramodKAvvaru** [comment] 2022-09-07 10:05
Sorry, I was working on master branch. Here are the logs taken using devel branch.
[connect_libnetconf2_devel_2.log](https://github.com/CESNET/libyang/files/9505096/connect_libnetconf2_devel_2.log)

**Comment by michalvasko** [comment] 2022-09-07 10:21
Sadly, they are not helpful. It seems the module is normally loaded into the context so I have no idea why it then fails to be found.

**Comment by PramodKAvvaru** [comment] 2022-09-13 15:14
I have done some debugging and found some of the modules gets unloaded from context after ietf-datastores error.
Modules are loaded in the order listed below until the ietf-datastores error. "notifications" is one of them. These modules also keep accumulating in ctx->unres->creating until datastore error after which it clears from the list. 

ietf-netconf-notifications
notifications
nc-notifications
ietf-x509-cert-to-name
ietf-keystore
ietf-netconf-with-defaults
ietf-datastores

**Comment by michalvasko** [comment] 2022-09-14 06:32
Right, sorry, I forgot about the rollback feature of the context. Please try the following patch and please provide the verbose output again so that I can make sure it works as intended, thanks.
```patch
diff --git a/src/session_client.c b/src/session_client.c
index 223630d..1a49451 100644
--- a/src/session_client.c
+++ b/src/session_client.c
@@ -660,19 +660,22 @@ nc_ctx_load_module(struct nc_session *session, const char *name, const char *rev
     struct clb_data_s clb_data;
 
     /* try to use a module from the context */
-    if (revision) {
-        *mod = ly_ctx_get_module(session->ctx, name, revision);
-    } else {
-        *mod = ly_ctx_get_module_implemented(session->ctx, name);
-        if (!*mod) {
+    *mod = ly_ctx_get_module_implemented(session->ctx, name);
+    if (!*mod) {
+        if (revision) {
+            *mod = ly_ctx_get_module(session->ctx, name, revision);
+        } else {
             *mod = ly_ctx_get_module_latest(session->ctx, name);
         }
+    } else if (revision && (!(*mod)->revision || strcmp((*mod)->revision, revision))) {
+        WRN(session, "Server implements module \"%s\" in revision \"%s\" but revision \"%s\" is already implemented"
+                " and will be used instead.", name, (*mod)->revision ? (*mod)->revision : "<none>", revision);
     }
 
     if (*mod) {
         /* make the present module implemented and/or enable all its features */
         if (lys_set_implemented(*mod, features)) {
-            ERR(session, "Failed to implement schema \"%s\".", (*mod)->name);
+            ERR(session, "Failed to implement module \"%s\".", (*mod)->name);
             ret = -1;
         }
     } else {
```

**Comment by PramodKAvvaru** [comment] 2022-09-14 10:36
Thanks @michalvasko, patch works! logs attached.
[subscribe_with_patch.txt](https://github.com/CESNET/libyang/files/9565509/subscribe_with_patch.txt)

**Comment by michalvasko** [comment] 2022-09-14 11:53
Great, committed but the revisions were switched in the original patch.

**Closed** 2023-02-07 11:13 UTC
Labels: is:bug, status:completed
