### ISSUE TITLE
YANG Schema Mount support?

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1225] opened 2020-10-06 17:03 UTC
Hi,

Do you have plan to support YANG Schema Mount? https://tools.ietf.org/html/rfc8528
I saw that L3 related IETF RFCs started to use it.

Thanks

**Comment by michalvasko** [comment] 2020-10-08 06:30
Hi,
yeah, we have planned to support it for quite some time now but there always seem to be some higher priority tasks. Unfortunately, this has not changed so I am not able to tell you anything more.

**Comment by awesomenode** [comment] 2020-10-08 07:22
Thanks for the info. It is good to know that this feature is planned.

**Comment by michalvasko** [comment] 2022-02-11 09:42
Duplicate of #691

**Closed by michalvasko** 2022-02-11 09:42 UTC
Labels: status:duplicate, is:enhancement
